/*      -*- linux-c -*-
 *
 * (C) Copyright IBM Corp. 2004
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  This
 * file and program are licensed under a BSD style license.  See
 * the Copying file included with the OpenHPI distribution for
 * full licensing terms.
 */

/******************************************************************* 
 * WARNING! This file is auto-magically generated by:
 *          ../../plugins/snmp_bc/eventmap2code.pl. 
 *          Do not change this file manually. Update script instead.
 *******************************************************************/

#ifndef __EL2EVENT_H
#define __EL2EVENT_H

#define HPIDUP_STRING  "_HPIDUP"

#define NO_OVR  0x0000  /* No overrides */
#define OVR_SEV 0x0001  /* Override Error Log's severity */
#define OVR_RID 0x0010  /* Override Error Log's source */
#define OVR_EXP 0x0100  /* Override Error Log's source for expansion cards */

typedef struct {
        gchar *event;
	SaHpiSeverityT event_sev;
	unsigned short event_ovr;
        short          event_dup;
} ErrLog2EventInfoT;

/* Global "Error Log to Event" mapping hash table and usage count */
extern GHashTable *errlog2event_hash;
extern unsigned int errlog2event_hash_use_count;

SaErrorT errlog2event_hash_init(struct snmp_bc_hnd *custom_handle);
SaErrorT errlog2event_hash_free(void);

/* XML event code and mapping structures */
extern char *eventxml;

struct errlog2event_hash_info {
        int platform;
	GHashTable *hashtable;
};

#endif
