/*      -*- linux-c -*-
 *
 * (C) Copyright IBM Corp. 2004
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  This
 * file and program are licensed under a BSD style license.  See
 * the Copying file included with the OpenHPI distribution for
 * full licensing terms.
 */

/******************************************************************* 
 * WARNING! This file is auto-magically generated by rsa_str2event.pl 
 *          Do not change this file manually. Update script instead
 *******************************************************************/

#ifndef __RSA_ERRORLOG_H
#define __RSA_ERRORLOG_H

#define EVT_RECOVERY "Recovery "
#define ER_STR_POST_LOG_CLEARED "System log cleared."
#define EVT_EN_LOG_FULL "System error log full"
#define LOG_LOGIN_CHAR "'"
#define LOG_READ_VALUE_STRING " Read value "
#define LOG_LOGIN_STRING "Login ID:"
#define LOG_THRESHOLD_VALUE_STRING " Threshold value "

#endif
