=head1 NAME


hpi_shell - An openhpi sample application that allows a user to interactively perform a number of HPI operations.

=head1 SYNOPSIS 

hpi_shell [-c <cfgfile>] [-e] [-f <file>] [-n <hostname>]

=head1 DESCRIPTION

hpi_shell reads commands and performs HPI operations based on those
commands.  This allows it to exercise HPI-managed hardware and do manual
operations on that hardware.

Once in hpi_shell, use the "help" command for a list of commands, or
"help command" for details on a particular command.

=head1 OPTIONS

=over 2

 -c     Use the specified openhpi config file
 -e     Show short events, discover after subscribe
 -f     Read commands from "file" rather than standard input
 -n     Connect to the OpenHPI daemon on "hostname" rather than the
 	one running on the local host
 -x	Produce extra debugging output

=back

=head1 SEE ALSO

  hpi_shell      hpifan         hpipower       hpithres       
  hpialarms      hpiinv         hpireset       hpitop         
  hpiel          hpijs          hpisensor      hpitree        
  hpievents      hpionIBMblade  hpisettime     hpiwdt

=head1 AUTHORS

Author(s) of this man page:

  Bryan Sutula (sutula@users.sourceforge.net)
