=head1 NAME

hpifan - An openhpi sample application that shows "Fan Control" management instruments

=head1 SYNOPSIS 

 hpifan [-D nn] [-h] [-s auto|nn] [-X]
 hpifan [--domain=nn] [--help] [--speed=auto|nn] [--debug]

=head1 DESCRIPTION

hpifan walks the RPT (Resource Present Table) for resouces that have 
"Fan Control" management instruments (SAHPI_CTRL_FAN_SPEED).

If no domain is selected, hpifan uses a session to the default domain. The selected domain id must be configured via the openhpidclient.conf file specified in the environment.

=head1 OPTIONS

=over 2

  -h, --help              Show help options
  -s, --speed=auto|nn     Set fan speed for ALL fans in domain
                          (Speed is a number or "auto" for setting fan in auto mode)
  -D, --domain=nn         Select domain id nn
  -X, --debug             Display debug messages

=back

=head1 SEE ALSO

         hpi_shell
         hpialarms      hpigensimdata  hpireset       hpitop
         hpidomain      hpiinv         hpisensor      hpitree
         hpiel          hpionIBMblade  hpisettime     hpiwdt
         hpievents      hpipower       hpithres       hpixml
         ohdomainlist   ohhandler      ohparam

 
=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)
 Ulrich Kleber (ulikleber@users.sourceforge.net)

