=head1 NAME

hpifan - An openhpi sample application that shows "Fan Control" management instruments

=head1 SYNOPSIS 

hpifan [-D domainid] [-h] [-s fan_speed_level]

=head1 DESCRIPTION

hpifan walks the RPT (Resource Present Table) for resouces that have 
"Fan Control" management instruments (SAHPI_CTRL_FAN_SPEED).

If no domain is selected, hpifan uses a session to the default domain. The selected domain id must be configured via the openhpidclient.conf file specified in the environment.

=head1 OPTIONS

=over 2

 -D <domainid> select domain id
 -s <speed>    set fan speed for ALL fans.
               <speed> is a number or "auto" for setting fan in auto mode
 -h            help

=back

=head1 SEE ALSO

         hpi_shell
         hpialarms      hpigensimdata  hpireset       hpitop
         hpidomain      hpiinv         hpisensor      hpitree
         hpiel          hpionIBMblade  hpisettime     hpiwdt
         hpievents      hpipower       hpithres

 
=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)
 Ulrich Kleber (ulikleber@users.sourceforge.net)

