=head1 NAME

hpipower - This sample openhpi application exercises HPI Power Management APIs. 

=head1 SYNOPSIS 

 hpipower [ -D nn ] [ -d -p -r -u -x -h] [ -b n ]
 hpipower [--domain nn] [--power-down --power-up --reset --unattended --debug --help] [--blade n ]

=head1 DESCRIPTION

hpipower searches the Resource Presence Table (RPT) for resources with Power Capability. It sends the requested power action to the selected target.

If no domain is selected, hpievents polls for events in the default domain. The selected domain id must be configured via the openhpidclient.conf file specified in the environment.


=head1 OPTIONS

=over 2

  -h, --help           Show help options
  -d, --power-down     Power down target object
  -p, --power-up       Power on target object
  -r, --reset          Reset target object
  -u, --unattended     Unattended
  -b, --blade=n        Specify blade n (1...n)
  -D, --domain=nn      Select domain id nn
  -X, --debug          Display debug messages

=back

=head1 SEE ALSO

         hpi_shell
         hpialarms      hpifan         hpireset       hpitop
         hpidomain      hpigensimdata  hpisensor      hpitree
         hpiel          hpiiinv        hpisettime     hpiwdt
         hpievents      hpionIBMblade  hpithres       hpixml
         ohdomainlist   ohhandler      ohparam


=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)
 Ulrich Kleber (ulikleber@users.sourceforge.net)

