=head1 NAME

hpithres -  This sample openhpi application interactively displays sensors and sensor info. 

=head1 SYNOPSIS 

 hpithres [-D nn] [-N host[:port]] [-C <cfgfile>] [-X] [-h]
 hpithres [--domain=nn] [--host=host[:port]] [--cfgfile=file] [--debug] [--help]

=head1 DESCRIPTION

hpithres interactively displays sensor info for resources with Sensor Capability. Resources, sensors,and sensor info can be individually selected.

If no domain or host is selected, hpithres uses the default domain as specified in the openhpiclient.conf file.

=head1 OPTIONS

=over 2

Help Options:
  -h, --help                   Show help options

Application Options:
  -D, --domain=nn              Select domain id nn
  -X, --debug                  Display debug messages
  -N, --host="host<:port>"     Open session to the domain served by the daemon 
                               at the specified URL (host:port)
                               This option overrides the OPENHPI_DAEMON_HOST and
                               OPENHPI_DAEMON_PORT environment variables.
  -C, --cfgfile="file"         Use passed file as client configuration file
                               This option overrides the OPENHPICLIENT_CONf
                               environment variable.


=back

=head1 SEE ALSO

         hpi_shell
         hpialarms      hpifan         hpipower       hpitop
         hpidomain      hpigensimdata  hpireset       hpitree
         hpiel          hpiiinv        hpisensor      hpiwdt
         hpievents      hpionIBMblade  hpisettime     hpixml
         ohdomainlist   ohhandler      ohparam


=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)
 Ulrich Kleber (ulikleber@users.sourceforge.net)

