=head1 NAME

hpitree - A openhpi sample application that shows in details the resources (rpt's)
and resources' manamegement instruments (rdr's) data structures of the managed openHPI complex. 

=head1 SYNOPSIS 

hpitree [-D id] [-acdiorsw -n resource -x]

=head1 DESCRIPTION

hpitree walks the Resource Presence Table (RPT) of the managed openHPI complex, and displays in details the resources (rpt's) and resources' management instruments (rdr's) data structures.

If no domain is selected, hpitop displays information using a session with the default domain. The selected domain id must be configured via the openhpidclient.conf file specified in the environment.


=head1 OPTIONS

=over 2

 (No Option) Display all rpts and rdrs
 -D nn  Select domain id nn
 -a     Display all rpts and rdrs
 -c     Display only controls
 -d     Display rdr records
 -i     Display only inventories
 -o     Display system overview: rpt & rdr headers
 -r     Display only rpts
 -s     Display only sensors
 -w     Display only watchdog
 -n nn  Select particular resource id to display
        (Used with [-cdirs] options)
 -x     Display debug messages

=back

=head1 SEE ALSO
  
         hpi_shell
         hpialarms      hpifan         hpipower       hpithres
         hpidomain      hpigensimdata  hpireset       hpitop
         hpiel          hpiiinv        hpisensor      hpiwdt
         hpievents      hpionIBMblade  hpisettime
         ohhandler      ohparam


=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)
 Ulrich Kleber (ulikleber@users.sourceforge.net)

