=head1 NAME

ohparam - An openhpi sample application that uses the openhpi additional interface to control openhpi configuration parameters

=head1 SYNOPSIS 

 ohparam [-D nn] [-N host[:port]] [-C <cfgfile>] [-X] get
 ohparam [-D nn] [-N host[:port]] [-C <cfgfile>] [-X] set <paramname newvalue>
 ohparam [--domain nn] [--host=host[:port]] [--cfgfile=file] [--debug] get
 ohparam [--domain nn] [--host=host[:port]] [--cfgfile=file] [--debug] set <paramname newvalue>

=head1 DESCRIPTION

ohparam get will display all global configuration parameters of the openhpi daemon for the specified domain.

ohparam set will change the given global configuration parameters of the openhpi daemon for the specified domain to the new value.

If no domain is selected, ohparam uses the default domain. The selected domain id must be configured via the openhpidclient.conf file specified in the environment.

=head1 COMMANDS

=over 2

 Command get: display info about all global parameters  
         no specific arguments                         

 Command set:                                           
         one of the daemon's global parameters:        
         (without the OPENHPI prefix)                  
           ON_EP, LOG_ON_SEV, EVT_QUEUE_LIMIT,         
           DEL_SIZE_LIMIT, DEL_SAVE                    
           DAT_SIZE_LIMIT, DAT_USER_LIMIT, DAT_SAVE    
           PATH, VARPATH, CONF                         
         and the desired new value. Example:           
           ohparam set DEL_SIZE_LIMIT 20000            

=back

=head1 OPTIONS

=over 2

Help Options:
  -h, --help                   Show help options

Application Options:
  -D, --domain=nn              Select domain id nn
  -X, --debug                  Display debug messages
  -N, --host="host<:port>"     Connect to daemon host:port
  -C, --cfgfile="file"         Use passed file as client configuration file


=back

=head1 SEE ALSO

         hpi_shell

         hpialarms      hpifan         hpipower       hpithres
         hpidomain      hpigensimdata  hpireset       hpitop
         hpiel          hpiiinv        hpisensor      hpitree
         hpievents      hpionIBMblade  hpisettime     hpiwdt
         hpixml
         ohdomainlist   ohhandler

 
=head1 AUTHORS

Authors of this man page:

 Ulrich Kleber (ulikleber@users.sourceforge.net)

