=head1 NAME

hpifan - An openhpi sample application that shows "Fan Control" management instruments

=head1 SYNOPSIS 

 hpifan [-D nn] [-N host[:port]] [-C <cfgfile>] [-h] [-s auto|nn] [-X]
 hpifan [--domain=nn] [--host=host[:port]] [--cfgfile=file] [--help] [--speed=auto|nn] [--debug]

=head1 DESCRIPTION

hpifan walks the RPT (Resource Present Table) for resouces that have 
"Fan Control" management instruments (SAHPI_CTRL_FAN_SPEED).

If no domain is selected, hpifan uses a session to the default domain. The selected domain id must be configured via the openhpidclient.conf file specified in the environment.

=head1 OPTIONS

=over 2

Help Options:
  -h, --help                   Show help options

Application Options:
  -s, --speed=auto|nn          Set fan speed for ALL fans in domain
                      speed is a number or "auto" for setting fan in auto mode
  -D, --domain=nn              Select domain id nn
  -X, --debug                  Display debug messages
  -N, --host="host<:port>"     Connect to daemon host:port
  -C, --cfgfile="file"         Use passed file as client configuration file


=back

=head1 SEE ALSO

         hpi_shell
         hpialarms      hpigensimdata  hpireset       hpitop
         hpidomain      hpiinv         hpisensor      hpitree
         hpiel          hpionIBMblade  hpisettime     hpiwdt
         hpievents      hpipower       hpithres       hpixml
         ohdomainlist   ohhandler      ohparam

 
=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)
 Ulrich Kleber (ulikleber@users.sourceforge.net)

