=head1 NAME

hpireset - This sample openhpi application exercises HPI Reset Management APIs. 

=head1 SYNOPSIS 

 hpireset [-D nn] [-r -w -h -X]
 hpireset [--domain nn] [--hard --warm --help --debug]

=head1 DESCRIPTION

hpireset searches the Resource Presence Table (RPT) for resources with Reset Capability. It sends the requested reset action to all resources with SAHPI_CAPABILITY_RESET.

If no domain is selected, hpireset uses a session with the default domain. The selected domain id must be configured via the openhpidclient.conf file specified in the environment.


=head1 OPTIONS

=over 2

  -h, --help          Show help options
  -r, --hard          hard resets the system
  -w, --warm          warm resets the system
  -D, --domain=nn     Select domain id nn
  -X, --debug         Display debug messages


=back

=head1 SEE ALSO

         hpi_shell
         hpialarms      hpifan         hpipower       hpitop
         hpidomain      hpigensimdata  hpisensor      hpitree
         hpiel          hpiiinv        hpisettime     hpiwdt
         hpievents      hpionIBMblade  hpithres       hpixml
         ohdomainlist   ohhandler      ohparam


=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)
 Ulrich Kleber (ulikleber@users.sourceforge.net)

