=head1 NAME

 hpisensor -  This sample openhpi application displays sensor info for all resources with Sensor Capability

=head1 SYNOPSIS 

 hpisensor [-D nn] [-t -r -s -X -h] [-E epath]
 hpisensor [--domain=nn] [--threshold --range --eventstate --debug --help] [--entity-path="epath"]

=head1 DESCRIPTION

hpisensor displays sensor info for all resources with Sensor Capability.
Option -E (entity-path) restricts the output on the specified entity-path.

If no domain is selected, hpisensor uses a session with the default domain. The selected domain id must be configured via the openhpidclient.conf file specified in the environment.


=head1 OPTIONS

=over 2

  -h, --help                    Show help options
  -t, --threshold               Show Thresholds also
  -r, --range                   Show Range values also
  -s, --eventstate              Show EventState also
  -D, --domain=nn               Select domain id nn
  -X, --debug                   Display debug messages
  -E, --entity-path="epath"     Use entity path epath

=back

=head1 SEE ALSO

         hpi_shell
         hpialarms      hpifan         hpipower       hpitop
         hpidomain      hpigensimdata  hpireset       hpitree
         hpiel          hpiiinv        hpisettime     hpiwdt
         hpievents      hpionIBMblade  hpithres       hpixml
         ohdomainlist   ohhandler      ohparam
 

=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)
 Ulrich Kleber (ulikleber@users.sourceforge.net)

