=head1 NAME

hpithres -  This sample openhpi application interactively displays sensors and sensor info. 

=head1 SYNOPSIS 

hpithres [-D domain] [-x]

=head1 DESCRIPTION

hpithres interactively displays sensor info for resources with Sensor Capability. Resources, sensors,and sensor info can be individually selected.

If no domain is selected, hpiel uses a session with the default domain. The selected domain id must be configured via the openhpidclient.conf file specified in the environment.

=head1 OPTIONS

=over 2

-D domainid  Select domain
-x           Display debug messages

=back

=head1 SEE ALSO

         hpi_shell
         hpialarms      hpifan         hpipower       hpitop
         hpidomain      hpigensimdata  hpireset       hpitree
         hpiel          hpiiinv        hpisensor      hpiwdt
         hpievents      hpionIBMblade  hpisettime
         ohdomainlist   ohhandler      ohparam


=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)
 Ulrich Kleber (ulikleber@users.sourceforge.net)

