=head1 NAME

hpxml - An openhpi sample application that displays system view in XML. 

=head1 SYNOPSIS 

 hpixml [-D nn] [-s] [-i -t ] [-N host[:port]] [-C=file] [-h]
 hpixml [--domain=nn] [--xsd] [--indent --text ] [--host=host[:port]] [--cfgfile=file] [--help]

=head1 DESCRIPTION

hpixml displays system view in XML.

If no domain is selected, hpixml uses a session with the default domain. The selected domain id must be configured via the openhpidclient.conf file specified in the environment.


=head1 OPTIONS

=over 2

Help Options:
  -h, --help                   Show help options

Application Options:
  -i, --indent                 Use indentation
  -t, --text                   Use enum and flag text names instead of raw values
  -s, --xsd                    Show XML schema
  -D, --domain=nn              Select domain id nn
  -N, --host="host<:port>"     Connect to daemon host:port
  -C, --cfgfile="file"         Use passed file as client configuration file

=back

=head1 SEE ALSO

         hpi_shell
         hpialarms      hpigensimdata  hpireset       hpitop
         hpidomain      hpiinv         hpisensor      hpitree
         hpievents      hpionIBMblade  hpisettime     hpiwdt
         hpifan         hpipower       hpithres
         ohdomainlist   ohhandler      ohparam


=head1 AUTHORS

Authors of this man page:

 Anton Pak (anton.pak@pigeonpoint.com)
 Ulrich Kleber (ulikleber@users.sourceforge.net)

