=head1 NAME

hpiwdt -  This sample openhpi application reads and enables the watchdog timer. 

=head1 SYNOPSIS 

 hpiwdt [-D nn] [-N host[:port]] [-C <cfgfile>] [-der -t sec] [-X] [-h]
 hpiwdt [--domain=nn] [--host=host[:port]] [--cfgfile=file]
        [--disable][--enable][--reset][--timout n] [--debug] [--help]

=head1 DESCRIPTION

hpiwdt reads and enables the watchdog timer. 

If no domain or host is selected, hpiwdt uses the default domain as specified in the openhpiclient.conf file.


=head1 OPTIONS

=over 2

Help Options:
  -h, --help                   Show help options

Application Options:
  -e, --enable                 enables the watchdog timer
  -d, --disable                disables the watchdog timer
  -r, --reset                  resets the watchdog timer
  -t, --timeout=n              sets timeout to n seconds
  -D, --domain=nn              Select domain id nn
  -X, --debug                  Display debug messages
  -N, --host="host<:port>"     Open session to the domain served by the daemon 
                               at the specified URL (host:port)
                               This option overrides the OPENHPI_DAEMON_HOST and
                               OPENHPI_DAEMON_PORT environment variables.
  -C, --cfgfile="file"         Use passed file as client configuration file
                               This option overrides the OPENHPICLIENT_CONf
                               environment variable.


=back

=head1 SEE ALSO

         hpi_shell
         hpialarms      hpifan         hpipower       hpithres
         hpidomain      hpigensimdata  hpireset       hpitop
         hpiel          hpiiinv        hpisensor      hpitree
         hpievents      hpionIBMblade  hpisettime     hpixml
         ohdomainlist   ohhandler      ohparam


=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)
 Ulrich Kleber (ulikleber@users.sourceforge.net)

