
#      -*- python -*-
#
# Copyright (C) 2012, Pigeon Point Systems
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  This
# file and program are licensed under a BSD style license.  See
# the Copying file included with the OpenHPI distribution for
# full licensing terms.
#
# Author(s):
#      Anton Pak <anton.pak@pigeonpoint.com>
#



#**********************************************************
# HPI Data Types (auto-generated)
#**********************************************************

#**********************************************************
# HPI Constants
#**********************************************************
SAHPI_TRUE = 1L
SAHPI_FALSE = 0L
SAHPI_MANUFACTURER_ID_UNSPECIFIED = 0L
SAHPI_INTERFACE_VERSION = 131842L
SA_OK = 0L
SA_HPI_ERR_BASE = -1000L
SA_ERR_HPI_ERROR = -1001L
SA_ERR_HPI_UNSUPPORTED_API = -1002L
SA_ERR_HPI_BUSY = -1003L
SA_ERR_HPI_INTERNAL_ERROR = -1004L
SA_ERR_HPI_INVALID_CMD = -1005L
SA_ERR_HPI_TIMEOUT = -1006L
SA_ERR_HPI_OUT_OF_SPACE = -1007L
SA_ERR_HPI_OUT_OF_MEMORY = -1008L
SA_ERR_HPI_INVALID_PARAMS = -1009L
SA_ERR_HPI_INVALID_DATA = -1010L
SA_ERR_HPI_NOT_PRESENT = -1011L
SA_ERR_HPI_NO_RESPONSE = -1012L
SA_ERR_HPI_DUPLICATE = -1013L
SA_ERR_HPI_INVALID_SESSION = -1014L
SA_ERR_HPI_INVALID_DOMAIN = -1015L
SA_ERR_HPI_INVALID_RESOURCE = -1016L
SA_ERR_HPI_INVALID_REQUEST = -1017L
SA_ERR_HPI_ENTITY_NOT_PRESENT = -1018L
SA_ERR_HPI_READ_ONLY = -1019L
SA_ERR_HPI_CAPABILITY = -1020L
SA_ERR_HPI_UNKNOWN = -1021L
SA_ERR_HPI_INVALID_STATE = -1022L
SA_ERR_HPI_UNSUPPORTED_PARAMS = -1023L
SAHPI_UNSPECIFIED_DOMAIN_ID = 4294967295L
SAHPI_UNSPECIFIED_RESOURCE_ID = 4294967295L
SAHPI_FIRST_ENTRY = 0L
SAHPI_LAST_ENTRY = 4294967295L
SAHPI_ENTRY_UNSPECIFIED = 0L
SAHPI_TIME_UNSPECIFIED = -9223372036854775808L
SAHPI_TIME_MAX_RELATIVE = 864691128455135232L
SAHPI_TIMEOUT_IMMEDIATE = 0L
SAHPI_TIMEOUT_BLOCK = -1L
SAHPI_MAX_TEXT_BUFFER_LENGTH = 255
SAHPI_ENT_IPMI_GROUP = 0L
SAHPI_ENT_SAFHPI_GROUP = 65536L
SAHPI_ENT_ROOT_VALUE = 65535L
SAHPI_MAX_ENTITY_PATH = 16
SAHPI_EC_UNSPECIFIED = 0L
SAHPI_EC_THRESHOLD = 1L
SAHPI_EC_USAGE = 2L
SAHPI_EC_STATE = 3L
SAHPI_EC_PRED_FAIL = 4L
SAHPI_EC_LIMIT = 5L
SAHPI_EC_PERFORMANCE = 6L
SAHPI_EC_SEVERITY = 7L
SAHPI_EC_PRESENCE = 8L
SAHPI_EC_ENABLE = 9L
SAHPI_EC_AVAILABILITY = 10L
SAHPI_EC_REDUNDANCY = 11L
SAHPI_EC_SENSOR_SPECIFIC = 126L
SAHPI_EC_GENERIC = 127L
SAHPI_ES_UNSPECIFIED = 0L
SAHPI_ES_LOWER_MINOR = 1L
SAHPI_ES_LOWER_MAJOR = 2L
SAHPI_ES_LOWER_CRIT = 4L
SAHPI_ES_UPPER_MINOR = 8L
SAHPI_ES_UPPER_MAJOR = 16L
SAHPI_ES_UPPER_CRIT = 32L
SAHPI_ES_IDLE = 1L
SAHPI_ES_ACTIVE = 2L
SAHPI_ES_BUSY = 4L
SAHPI_ES_STATE_DEASSERTED = 1L
SAHPI_ES_STATE_ASSERTED = 2L
SAHPI_ES_PRED_FAILURE_DEASSERT = 1L
SAHPI_ES_PRED_FAILURE_ASSERT = 2L
SAHPI_ES_LIMIT_NOT_EXCEEDED = 1L
SAHPI_ES_LIMIT_EXCEEDED = 2L
SAHPI_ES_PERFORMANCE_MET = 1L
SAHPI_ES_PERFORMANCE_LAGS = 2L
SAHPI_ES_OK = 1L
SAHPI_ES_MINOR_FROM_OK = 2L
SAHPI_ES_MAJOR_FROM_LESS = 4L
SAHPI_ES_CRITICAL_FROM_LESS = 8L
SAHPI_ES_MINOR_FROM_MORE = 16L
SAHPI_ES_MAJOR_FROM_CRITICAL = 32L
SAHPI_ES_CRITICAL = 64L
SAHPI_ES_MONITOR = 128L
SAHPI_ES_INFORMATIONAL = 256L
SAHPI_ES_ABSENT = 1L
SAHPI_ES_PRESENT = 2L
SAHPI_ES_DISABLED = 1L
SAHPI_ES_ENABLED = 2L
SAHPI_ES_RUNNING = 1L
SAHPI_ES_TEST = 2L
SAHPI_ES_POWER_OFF = 4L
SAHPI_ES_ON_LINE = 8L
SAHPI_ES_OFF_LINE = 16L
SAHPI_ES_OFF_DUTY = 32L
SAHPI_ES_DEGRADED = 64L
SAHPI_ES_POWER_SAVE = 128L
SAHPI_ES_INSTALL_ERROR = 256L
SAHPI_ES_FULLY_REDUNDANT = 1L
SAHPI_ES_REDUNDANCY_LOST = 2L
SAHPI_ES_REDUNDANCY_DEGRADED = 4L
SAHPI_ES_REDUNDANCY_LOST_SUFFICIENT_RESOURCES = 8L
SAHPI_ES_NON_REDUNDANT_SUFFICIENT_RESOURCES = 16L
SAHPI_ES_NON_REDUNDANT_INSUFFICIENT_RESOURCES = 32L
SAHPI_ES_REDUNDANCY_DEGRADED_FROM_FULL = 64L
SAHPI_ES_REDUNDANCY_DEGRADED_FROM_NON = 128L
SAHPI_ES_STATE_00 = 1L
SAHPI_ES_STATE_01 = 2L
SAHPI_ES_STATE_02 = 4L
SAHPI_ES_STATE_03 = 8L
SAHPI_ES_STATE_04 = 16L
SAHPI_ES_STATE_05 = 32L
SAHPI_ES_STATE_06 = 64L
SAHPI_ES_STATE_07 = 128L
SAHPI_ES_STATE_08 = 256L
SAHPI_ES_STATE_09 = 512L
SAHPI_ES_STATE_10 = 1024L
SAHPI_ES_STATE_11 = 2048L
SAHPI_ES_STATE_12 = 4096L
SAHPI_ES_STATE_13 = 8192L
SAHPI_ES_STATE_14 = 16384L
SAHPI_STANDARD_SENSOR_MIN = 256L
SAHPI_STANDARD_SENSOR_MAX = 511L
SAHPI_SENSOR_TYPE_SAFHPI_GROUP = 65536L
SAHPI_SENSOR_BUFFER_LENGTH = 32
SAHPI_ALL_EVENT_STATES = 65535L
SAHPI_SRF_MIN = 16L
SAHPI_SRF_MAX = 8L
SAHPI_SRF_NORMAL_MIN = 4L
SAHPI_SRF_NORMAL_MAX = 2L
SAHPI_SRF_NOMINAL = 1L
SAHPI_STM_LOW_MINOR = 1L
SAHPI_STM_LOW_MAJOR = 2L
SAHPI_STM_LOW_CRIT = 4L
SAHPI_STM_UP_MINOR = 8L
SAHPI_STM_UP_MAJOR = 16L
SAHPI_STM_UP_CRIT = 32L
SAHPI_STM_UP_HYSTERESIS = 64L
SAHPI_STM_LOW_HYSTERESIS = 128L
SAHPI_DEFAGSENS_OPER = 256L
SAHPI_DEFAGSENS_PWR = 257L
SAHPI_DEFAGSENS_TEMP = 258L
SAHPI_DEFAGSENS_MIN = 256L
SAHPI_DEFAGSENS_MAX = 271L
SAHPI_CTRL_MAX_STREAM_LENGTH = 4
SAHPI_TLN_ALL_LINES = 0L
SAHPI_CTRL_MAX_OEM_BODY_LENGTH = 255
SAHPI_CTRL_OEM_CONFIG_LENGTH = 10
SAHPI_DEFAULT_INVENTORY_ID = 0L
SAHPI_DEFAULT_WATCHDOG_NUM = 0L
SAHPI_WATCHDOG_EXP_BIOS_FRB2 = 2L
SAHPI_WATCHDOG_EXP_BIOS_POST = 4L
SAHPI_WATCHDOG_EXP_OS_LOAD = 8L
SAHPI_WATCHDOG_EXP_SMS_OS = 16L
SAHPI_WATCHDOG_EXP_OEM = 32L
SAHPI_DIMITEST_MAX_PARAMETERS = 10
SAHPI_DIMITEST_PARAM_NAME_LEN = 20
SAHPI_DIMITEST_CAPABILITY_NO_CAPABILITY = 0L
SAHPI_DIMITEST_CAPABILITY_RESULTSOUTPUT = 1L
SAHPI_DIMITEST_CAPABILITY_SERVICEMODE = 2L
SAHPI_DIMITEST_CAPABILITY_LOOPCOUNT = 4L
SAHPI_DIMITEST_CAPABILITY_LOOPTIME = 8L
SAHPI_DIMITEST_CAPABILITY_LOGGING = 16L
SAHPI_DIMITEST_CAPABILITY_TESTCANCEL = 32L
SAHPI_DIMITEST_CAPAB_RES_FINALONLY = 0L
SAHPI_DIMITEST_CAPAB_RES_ONDEMAND = 1L
SAHPI_DIMITEST_CAPAB_RES_ASYNC = 2L
SAHPI_DIMITEST_MAX_ENTITIESIMPACTED = 5
SAHPI_FUMI_MAX_OEM_BODY_LENGTH = 255
SAHPI_FUMI_MAX_ENTITIES_IMPACTED = 5
SAHPI_FUMI_NO_MAIN_PERSISTENT_COPY = 1L
SAHPI_FUMI_PROT_TFTP = 1L
SAHPI_FUMI_PROT_FTP = 2L
SAHPI_FUMI_PROT_HTTP = 4L
SAHPI_FUMI_PROT_LDAP = 8L
SAHPI_FUMI_PROT_LOCAL = 16L
SAHPI_FUMI_PROT_NFS = 32L
SAHPI_FUMI_PROT_DBACCESS = 64L
SAHPI_FUMI_CAP_ROLLBACK = 1L
SAHPI_FUMI_CAP_BANKCOPY = 2L
SAHPI_FUMI_CAP_BANKREORDER = 4L
SAHPI_FUMI_CAP_BACKUP = 8L
SAHPI_FUMI_CAP_TARGET_VERIFY = 16L
SAHPI_FUMI_CAP_TARGET_VERIFY_MAIN = 32L
SAHPI_FUMI_CAP_COMPONENTS = 64L
SAHPI_FUMI_CAP_AUTOROLLBACK = 128L
SAHPI_FUMI_CAP_AUTOROLLBACK_CAN_BE_DISABLED = 256L
SAHPI_FUMI_CAP_MAIN_NOT_PERSISTENT = 512L
SAHPI_SOD_TRIGGER_READING = 1L
SAHPI_SOD_TRIGGER_THRESHOLD = 2L
SAHPI_SOD_OEM = 4L
SAHPI_SOD_PREVIOUS_STATE = 8L
SAHPI_SOD_CURRENT_STATE = 16L
SAHPI_SOD_SENSOR_SPECIFIC = 32L
SAHPI_SEOD_CURRENT_STATE = 16L
SAHPI_SEOD_ALARM_STATES = 64L
SAHPI_EVT_QUEUE_OVERFLOW = 1L
SA_HPI_MAX_NAME_LENGTH = 256
SAHPI_LOAD_ID_DEFAULT = 0L
SAHPI_LOAD_ID_BYNAME = 4294967295L
SAHPI_GUID_LENGTH = 16
SAHPI_CAPABILITY_RESOURCE = 1073741824L
SAHPI_CAPABILITY_FUMI = 65536L
SAHPI_CAPABILITY_EVT_DEASSERTS = 32768L
SAHPI_CAPABILITY_DIMI = 16384L
SAHPI_CAPABILITY_AGGREGATE_STATUS = 8192L
SAHPI_CAPABILITY_CONFIGURATION = 4096L
SAHPI_CAPABILITY_MANAGED_HOTSWAP = 2048L
SAHPI_CAPABILITY_WATCHDOG = 1024L
SAHPI_CAPABILITY_CONTROL = 512L
SAHPI_CAPABILITY_FRU = 256L
SAHPI_CAPABILITY_LOAD_ID = 128L
SAHPI_CAPABILITY_ANNUNCIATOR = 64L
SAHPI_CAPABILITY_POWER = 32L
SAHPI_CAPABILITY_RESET = 16L
SAHPI_CAPABILITY_INVENTORY_DATA = 8L
SAHPI_CAPABILITY_EVENT_LOG = 4L
SAHPI_CAPABILITY_RDR = 2L
SAHPI_CAPABILITY_SENSOR = 1L
SAHPI_HS_CAPABILITY_AUTOEXTRACT_READ_ONLY = 2147483648L
SAHPI_HS_CAPABILITY_INDICATOR_SUPPORTED = 1073741824L
SAHPI_HS_CAPABILITY_AUTOINSERT_IMMEDIATE = 536870912L
SAHPI_DOMAIN_CAP_AUTOINSERT_READ_ONLY = 1L
SAHPI_EVTLOG_CAPABILITY_ENTRY_ADD = 1L
SAHPI_EVTLOG_CAPABILITY_CLEAR = 2L
SAHPI_EVTLOG_CAPABILITY_TIME_SET = 4L
SAHPI_EVTLOG_CAPABILITY_STATE_SET = 8L
SAHPI_EVTLOG_CAPABILITY_OVERFLOW_RESET = 16L
SAHPI_OLDEST_ENTRY = 0L
SAHPI_NEWEST_ENTRY = 4294967295L
SAHPI_NO_MORE_ENTRIES = 4294967294L
ATCAHPI_PICMG_MID = 12634L
ATCAHPI_BLINK_COLOR_LED = 128L
ATCAHPI_LED_WHITE = 64L
ATCAHPI_LED_ORANGE = 32L
ATCAHPI_LED_AMBER = 16L
ATCAHPI_LED_GREEN = 8L
ATCAHPI_LED_RED = 4L
ATCAHPI_LED_BLUE = 2L
ATCAHPI_CTRL_NUM_BLUE_LED = 0L
ATCAHPI_CTRL_NUM_LED1 = 1L
ATCAHPI_CTRL_NUM_LED2 = 2L
ATCAHPI_CTRL_NUM_LED3 = 3L
ATCAHPI_CTRL_NUM_APP_LED = 4L
ATCAHPI_RESOURCE_AGGREGATE_LED = 255L
ATCAHPI_ENT_POWER_ENTRY_MODULE_SLOT = 145L
ATCAHPI_ENT_SHELF_FRU_DEVICE_SLOT = 146L
ATCAHPI_ENT_SHELF_MANAGER_SLOT = 147L
ATCAHPI_ENT_FAN_TRAY_SLOT = 148L
ATCAHPI_ENT_FAN_FILTER_TRAY_SLOT = 149L
ATCAHPI_ENT_ALARM_SLOT = 150L
ATCAHPI_ENT_AMC_SLOT = 151L
ATCAHPI_ENT_PMC_SLOT = 152L
ATCAHPI_ENT_RTM_SLOT = 153L
ATCAHPI_ENT_PICMG_FRONT_BLADE = 65558L
ATCAHPI_ENT_SHELF_FRU_DEVICE = 65559L
ATCAHPI_ENT_FILTRATION_UNIT = 65560L
ATCAHPI_ENT_AMC = 65561L
ATCAHPI_SENSOR_NUM_SHELF_INFO_VALID = 4096L
ATCAHPI_CTRL_NUM_SHELF_ADDRESS = 4096L
ATCAHPI_CTRL_NUM_SHELF_IP_ADDRESS = 4097L
ATCAHPI_CTRL_NUM_SHELF_STATUS = 4098L
ATCAHPI_SENSOR_NUM_PWRONSEQ_COMMIT_STATUS = 4864L
ATCAHPI_CTRL_NUM_FRU_POWER_ON_SEQUENCE_COMMIT = 4864L
ATCAHPI_CTRL_NUM_FRU_POWER_ON_SEQUENCE = 4865L
ATCAHPI_CS_CPS_PWR_ON = 1L
ATCAHPI_CS_CPS_PWR_OVERLOAD = 2L
ATCAHPI_CS_CPS_INTERLOCK = 4L
ATCAHPI_CS_CPS_PWR_FAULT = 8L
ATCAHPI_CS_CPS__PWR_CTRL_FAULT = 16L
ATCAHPI_CS_CPS_PWR_RESTORE_PWR_UP_PREV = 32L
ATCAHPI_CS_CPS_PWR_RESTORE_PWR_UP = 64L
ATCAHPI_CS_CPS_PWR_RESTORE_UNKNOWN = 96L
ATCAHPI_CS_LPEVT_AC_FAILED = 1L
ATCAHPI_CS_LPEVT_PWR_OVERLOAD = 2L
ATCAHPI_CS_LPEVT_PWR_INTERLOCK = 4L
ATCAHPI_CS_LPEVT_PWR_FAULT = 8L
ATCAHPI_CS_LPEVT_PWRON_IPMI = 16L
ATCAHPI_CS_MISC_CS_INTRUSION_ACTIVE = 1L
ATCAHPI_CS_MISC_CS_FP_LOCKOUT_ACTIVE = 2L
ATCAHPI_CS_MISC_CS_DRIVE_FAULT = 4L
ATCAHPI_CS_MISC_CS_COOLING_FAULT = 8L
ATCAHPI_CS_FP_BUTTON_PWR_OFF = 1L
ATCAHPI_CS_FP_BUTTON_RESET_OFF = 2L
ATCAHPI_CS_FP_BUTTON_DIAGINTR_OFF = 4L
ATCAHPI_CS_FP_BUTTON_STANDBY_OFF = 8L
ATCAHPI_CS_FP_BUTTON_ALLOW_PWR_OFF = 16L
ATCAHPI_CS_FP_BUTTON_ALLOW_RESET_OFF = 32L
ATCAHPI_CS_FP_BUTTON_ALLOW_DIAGINTR_OFF = 64L
ATCAHPI_CS_FP_BUTTON_ALLOW_STANDBY_OFF = 128L
ATCAHPI_SENSOR_NUM_SHMGR_REDUNDANCY = 4097L
ATCAHPI_SENSOR_NUM_SHMGR_ACTIVE = 4098L
ATCAHPI_SENSOR_NUM_SHMGR_STANDBY = 4099L
ATCAHPI_CTRL_NUM_SHMGR_FAILOVER = 4112L
ATCAHPI_CTRL_NUM_FAILED_RESOURCE_EXTRACT = 4126L
ATCAHPI_SENSOR_NUM_SLOT_STATE = 4112L
ATCAHPI_SENSOR_NUM_ASSIGNED_PWR = 4113L
ATCAHPI_SENSOR_NUM_MAX_PWR = 4114L
ATCAHPI_CTRL_NUM_FRU_ACTIVATION = 4128L
ATCAHPI_SENSOR_NUM_IPMB0 = 4352L
ATCAHPI_CTRL_NUM_DESIRED_PWR = 4144L
ATCAHPI_CTRL_NUM_IPMB_A_STATE = 4353L
ATCAHPI_CTRL_NUM_IPMB_B_STATE = 4354L
ATCAHPI_CTRL_NUM_FRU_CONTROL = 4608L
ATCAHPI_CTRL_NUM_FRU_IPMC_RESET = 4609L
ATCAHPI_SENSOR_NUM_AMC_PWRONSEQ_COMMIT_STATUS = 5376L
ATCAHPI_CTRL_NUM_AMC_POWER_ON_SEQUENCE_COMMIT = 5376L
ATCAHPI_CTRL_NUM_AMC_POWER_ON_SEQUENCE = 5377L
ATCAHPI_CTRL_NUM_FAN_SPEED = 5120L
ATCAHPI_PICMG_CT_CHASSIS_STATUS = 16789850L
ATCAHPI_PICMG_CT_ATCA_LED = 33567066L
XTCAHPI_SPEC_VERSION = 4228711L
XTCAHPI_PICMG_MID = 12634L
XTCAHPI_ENT_POWER_SLOT = 145L
XTCAHPI_ENT_SHELF_FRU_DEVICE_SLOT = 146L
XTCAHPI_ENT_SHELF_MANAGER_SLOT = 147L
XTCAHPI_ENT_FAN_TRAY_SLOT = 148L
XTCAHPI_ENT_FAN_FILTER_TRAY_SLOT = 149L
XTCAHPI_ENT_ALARM_SLOT = 150L
XTCAHPI_ENT_AMC_SLOT = 151L
XTCAHPI_ENT_PMC_SLOT = 152L
XTCAHPI_ENT_RTM_SLOT = 153L
XTCAHPI_ENT_CARRIER_MANAGER_SLOT = 154L
XTCAHPI_ENT_CARRIER_SLOT = 155L
XTCAHPI_ENT_COM_E_SLOT = 156L
XTCAHPI_CTRL_NUM_IP_ADDRESS_0 = 4097L
XTCAHPI_CTRL_NUM_IP_ADDRESS_1 = 4099L
XTCAHPI_CTRL_NUM_POWER_ON_SEQUENCE = 4865L
XTCAHPI_CTRL_NUM_POWER_ON_SEQUENCE_COMMIT = 4864L
XTCAHPI_SENSOR_NUM_PWRONSEQ_COMMIT_STATUS = 4864L
XTCAHPI_ANN_NUM_TELCO_ALARM = 4096L
XTCAHPI_SENSOR_NUM_REDUNDANCY = 4097L
XTCAHPI_SENSOR_NUM_ACTIVE = 4098L
XTCAHPI_SENSOR_NUM_STANDBY = 4099L
XTCAHPI_CTRL_NUM_FAILOVER = 4112L
XTCAHPI_CTRL_NUM_ACTIVATION = 4128L
XTCAHPI_CTRL_NUM_DEACTIVATION = 4129L
XTCAHPI_SENSOR_NUM_FRU_INFO_VALID = 4096L
XTCAHPI_SENSOR_NUM_ASSIGNED_PWR = 4113L
XTCAHPI_SENSOR_NUM_SLOT_ASSIGNED_PWR = 6144L
XTCAHPI_IDR_NUM_CONFIG_INFO = 1L
XTCAHPI_CTRL_NUM_SHELF_ADDRESS = 4096L
XTCAHPI_CTRL_NUM_SHELF_STATUS = 4098L
XTCAHPI_CTRL_NUM_SHELF_MANAGER_RMCP_USERNAME = 4177L
XTCAHPI_CTRL_NUM_SHELF_MANAGER_RMCP_PASSWORD = 4178L
XTCAHPI_CTRL_NUM_IN_SHELF_ACTIVATION = 4192L
XTCAHPI_CTRL_NUM_IN_SHELF_DEACTIVATION = 4193L
XTCAHPI_CTRL_NUM_DESIRED_PWR = 4144L
XTCAHPI_SENSOR_NUM_IPMB0 = 4352L
XTCAHPI_CTRL_NUM_IPMB_A_STATE = 4353L
XTCAHPI_CTRL_NUM_IPMB_B_STATE = 4354L
XTCAHPI_CTRL_NUM_FRU_CONTROL = 4608L
XTCAHPI_CTRL_NUM_FRU_IPMC_RESET = 4609L
XTCAHPI_CTRL_NUM_BLUE_LED = 0L
XTCAHPI_CTRL_NUM_LED1 = 1L
XTCAHPI_CTRL_NUM_LED2 = 2L
XTCAHPI_CTRL_NUM_LED3 = 3L
XTCAHPI_CTRL_NUM_APP_LED = 4L
XTCAHPI_RESOURCE_AGGREGATE_LED = 255L
XTCAHPI_CTRL_NUM_AMC_POWER_ON_SEQUENCE = 5377L
XTCAHPI_CTRL_NUM_AMC_POWER_ON_SEQUENCE_COMMIT = 5376L
XTCAHPI_SENSOR_NUM_AMC_PWRONSEQ_COMMIT_STATUS = 5376L
XTCAHPI_CTRL_NUM_FAN_SPEED = 5120L
XTCAHPI_SENSOR_NUM_HPM1_IPMC_GLOBAL_CAPS = 5888L
XTCAHPI_SENSOR_NUM_HPM1_IMAGE_CAPS = 5889L
XTCAHPI_SENSOR_NUM_HPM1_ROLLBACK_TIMEOUT = 5890L
XTCAHPI_CTRL_NUM_CRITICAL_TELCO_ALARM = 5632L
XTCAHPI_CTRL_NUM_MAJOR_TELCO_ALARM = 5633L
XTCAHPI_CTRL_NUM_MINOR_TELCO_ALARM = 5634L
XTCAHPI_CTRL_NUM_POWER_TELCO_ALARM = 5635L
XTCAHPI_CTRL_NUM_TELCO_ALARM_CUTOFF = 5636L
XTCAHPI_SENSOR_NUM_TELCO_ALARM_INPUT = 5632L
XTCAHPI_INDICATOR_LOC_MINOR_ALARM = 0L
XTCAHPI_INDICATOR_LOC_MAJOR_ALARM = 1L
XTCAHPI_INDICATOR_LOC_CRITICAL_ALARM = 2L
XTCAHPI_INDICATOR_LOC_POWER_ALARM = 3L
XTCAHPI_CONFIG_DATA_AREA_SPEC_VERSION = 0L
XTCAHPI_CONFIG_DATA_FIELD_LABEL = 0L
XTCAHPI_CS_CPS_PWR_ON = 1L
XTCAHPI_CS_CPS_PWR_OVERLOAD = 2L
XTCAHPI_CS_CPS_INTERLOCK = 4L
XTCAHPI_CS_CPS_PWR_FAULT = 8L
XTCAHPI_CS_CPS_PWR_CTRL_FAULT = 16L
XTCAHPI_CS_CPS_PWR_RESTORE_PWR_UP_PREV = 32L
XTCAHPI_CS_CPS_PWR_RESTORE_PWR_UP = 64L
XTCAHPI_CS_CPS_PWR_RESTORE_UNKNOWN = 96L
XTCAHPI_CS_LPEVT_AC_FAILED = 1L
XTCAHPI_CS_LPEVT_PWR_OVERLOAD = 2L
XTCAHPI_CS_LPEVT_PWR_INTERLOCK = 4L
XTCAHPI_CS_LPEVT_PWR_FAULT = 8L
XTCAHPI_CS_LPEVT_PWRON_IPMI = 16L
XTCAHPI_CS_MISC_CS_INTRUSION_ACTIVE = 1L
XTCAHPI_CS_MISC_CS_FP_LOCKOUT_ACTIVE = 2L
XTCAHPI_CS_MISC_CS_DRIVE_FAULT = 4L
XTCAHPI_CS_MISC_CS_COOLING_FAULT = 8L
XTCAHPI_CS_FP_BUTTON_PWR_OFF = 1L
XTCAHPI_CS_FP_BUTTON_RESET_OFF = 2L
XTCAHPI_CS_FP_BUTTON_DIAGINTR_OFF = 4L
XTCAHPI_CS_FP_BUTTON_STANDBY_OFF = 8L
XTCAHPI_CS_FP_BUTTON_ALLOW_PWR_OFF = 16L
XTCAHPI_CS_FP_BUTTON_ALLOW_RESET_OFF = 32L
XTCAHPI_CS_FP_BUTTON_ALLOW_DIAGINTR_OFF = 64L
XTCAHPI_CS_FP_BUTTON_ALLOW_STANDBY_OFF = 128L
XTCAHPI_BLINK_COLOR_LED = 128L
XTCAHPI_LED_WHITE = 64L
XTCAHPI_LED_ORANGE = 32L
XTCAHPI_LED_AMBER = 16L
XTCAHPI_LED_GREEN = 8L
XTCAHPI_LED_RED = 4L
XTCAHPI_LED_BLUE = 2L
XTCAHPI_IF_FABRIC = 1L
XTCAHPI_IF_SYNC_CLOCK = 2L
XTCAHPI_IF_BASE = 3L
XTCAHPI_IF_UPDATE_CHANNEL = 4L
XTCAHPI_IF_METALLIC_TEST = 5L
XTCAHPI_IF_RINGING_GENERATOR_BUS = 6L
XTCAHPI_CONFIG_DATA_LOC_DEFAULT = 0L
XTCAHPI_CONFIG_DATA_LOC_SHELF_ADDRESS = 1L
XTCAHPI_CONFIG_DATA_LOC_POWER_ON_SEQUENCE = 2L
XTCAHPI_CONFIG_DATA_LOC_CHASSIS_STATUS = 3L
XTCAHPI_CONFIG_DATA_LOC_ACTIVATION = 4L
XTCAHPI_CONFIG_DATA_LOC_DEACTIVATION = 5L
XTCAHPI_CONFIG_DATA_LOC_IN_SHELF_ACTIVATION = 6L
XTCAHPI_CONFIG_DATA_LOC_IN_SHELF_DEACTIVATION = 7L
XTCAHPI_CONFIG_DATA_LOC_USERNAME = 8L
XTCAHPI_CONFIG_DATA_LOC_PASSWORD = 9L
XTCAHPI_CONFIG_DATA_LOC_FUMI_GLOBAL_UPGRADE_CAP = 10L
XTCAHPI_CONFIG_DATA_LOC_FUMI_UPGRADE_IMAGE_CAP = 11L
XTCAHPI_CONFIG_DATA_LOC_FUMI_ROLLBACK_TIMEOUT = 12L
SAHPI_LANG_UNDEF = 0L
SAHPI_LANG_AFAR = 1L
SAHPI_LANG_ABKHAZIAN = 2L
SAHPI_LANG_AFRIKAANS = 3L
SAHPI_LANG_AMHARIC = 4L
SAHPI_LANG_ARABIC = 5L
SAHPI_LANG_ASSAMESE = 6L
SAHPI_LANG_AYMARA = 7L
SAHPI_LANG_AZERBAIJANI = 8L
SAHPI_LANG_BASHKIR = 9L
SAHPI_LANG_BYELORUSSIAN = 10L
SAHPI_LANG_BULGARIAN = 11L
SAHPI_LANG_BIHARI = 12L
SAHPI_LANG_BISLAMA = 13L
SAHPI_LANG_BENGALI = 14L
SAHPI_LANG_TIBETAN = 15L
SAHPI_LANG_BRETON = 16L
SAHPI_LANG_CATALAN = 17L
SAHPI_LANG_CORSICAN = 18L
SAHPI_LANG_CZECH = 19L
SAHPI_LANG_WELSH = 20L
SAHPI_LANG_DANISH = 21L
SAHPI_LANG_GERMAN = 22L
SAHPI_LANG_BHUTANI = 23L
SAHPI_LANG_GREEK = 24L
SAHPI_LANG_ENGLISH = 25L
SAHPI_LANG_ESPERANTO = 26L
SAHPI_LANG_SPANISH = 27L
SAHPI_LANG_ESTONIAN = 28L
SAHPI_LANG_BASQUE = 29L
SAHPI_LANG_PERSIAN = 30L
SAHPI_LANG_FINNISH = 31L
SAHPI_LANG_FIJI = 32L
SAHPI_LANG_FAEROESE = 33L
SAHPI_LANG_FRENCH = 34L
SAHPI_LANG_FRISIAN = 35L
SAHPI_LANG_IRISH = 36L
SAHPI_LANG_SCOTSGAELIC = 37L
SAHPI_LANG_GALICIAN = 38L
SAHPI_LANG_GUARANI = 39L
SAHPI_LANG_GUJARATI = 40L
SAHPI_LANG_HAUSA = 41L
SAHPI_LANG_HINDI = 42L
SAHPI_LANG_CROATIAN = 43L
SAHPI_LANG_HUNGARIAN = 44L
SAHPI_LANG_ARMENIAN = 45L
SAHPI_LANG_INTERLINGUA = 46L
SAHPI_LANG_INTERLINGUE = 47L
SAHPI_LANG_INUPIAK = 48L
SAHPI_LANG_INDONESIAN = 49L
SAHPI_LANG_ICELANDIC = 50L
SAHPI_LANG_ITALIAN = 51L
SAHPI_LANG_HEBREW = 52L
SAHPI_LANG_JAPANESE = 53L
SAHPI_LANG_YIDDISH = 54L
SAHPI_LANG_JAVANESE = 55L
SAHPI_LANG_GEORGIAN = 56L
SAHPI_LANG_KAZAKH = 57L
SAHPI_LANG_GREENLANDIC = 58L
SAHPI_LANG_CAMBODIAN = 59L
SAHPI_LANG_KANNADA = 60L
SAHPI_LANG_KOREAN = 61L
SAHPI_LANG_KASHMIRI = 62L
SAHPI_LANG_KURDISH = 63L
SAHPI_LANG_KIRGHIZ = 64L
SAHPI_LANG_LATIN = 65L
SAHPI_LANG_LINGALA = 66L
SAHPI_LANG_LAOTHIAN = 67L
SAHPI_LANG_LITHUANIAN = 68L
SAHPI_LANG_LATVIANLETTISH = 69L
SAHPI_LANG_MALAGASY = 70L
SAHPI_LANG_MAORI = 71L
SAHPI_LANG_MACEDONIAN = 72L
SAHPI_LANG_MALAYALAM = 73L
SAHPI_LANG_MONGOLIAN = 74L
SAHPI_LANG_MOLDAVIAN = 75L
SAHPI_LANG_MARATHI = 76L
SAHPI_LANG_MALAY = 77L
SAHPI_LANG_MALTESE = 78L
SAHPI_LANG_BURMESE = 79L
SAHPI_LANG_NAURU = 80L
SAHPI_LANG_NEPALI = 81L
SAHPI_LANG_DUTCH = 82L
SAHPI_LANG_NORWEGIAN = 83L
SAHPI_LANG_OCCITAN = 84L
SAHPI_LANG_AFANOROMO = 85L
SAHPI_LANG_ORIYA = 86L
SAHPI_LANG_PUNJABI = 87L
SAHPI_LANG_POLISH = 88L
SAHPI_LANG_PASHTOPUSHTO = 89L
SAHPI_LANG_PORTUGUESE = 90L
SAHPI_LANG_QUECHUA = 91L
SAHPI_LANG_RHAETOROMANCE = 92L
SAHPI_LANG_KIRUNDI = 93L
SAHPI_LANG_ROMANIAN = 94L
SAHPI_LANG_RUSSIAN = 95L
SAHPI_LANG_KINYARWANDA = 96L
SAHPI_LANG_SANSKRIT = 97L
SAHPI_LANG_SINDHI = 98L
SAHPI_LANG_SANGRO = 99L
SAHPI_LANG_SERBOCROATIAN = 100L
SAHPI_LANG_SINGHALESE = 101L
SAHPI_LANG_SLOVAK = 102L
SAHPI_LANG_SLOVENIAN = 103L
SAHPI_LANG_SAMOAN = 104L
SAHPI_LANG_SHONA = 105L
SAHPI_LANG_SOMALI = 106L
SAHPI_LANG_ALBANIAN = 107L
SAHPI_LANG_SERBIAN = 108L
SAHPI_LANG_SISWATI = 109L
SAHPI_LANG_SESOTHO = 110L
SAHPI_LANG_SUDANESE = 111L
SAHPI_LANG_SWEDISH = 112L
SAHPI_LANG_SWAHILI = 113L
SAHPI_LANG_TAMIL = 114L
SAHPI_LANG_TELUGU = 115L
SAHPI_LANG_TAJIK = 116L
SAHPI_LANG_THAI = 117L
SAHPI_LANG_TIGRINYA = 118L
SAHPI_LANG_TURKMEN = 119L
SAHPI_LANG_TAGALOG = 120L
SAHPI_LANG_SETSWANA = 121L
SAHPI_LANG_TONGA = 122L
SAHPI_LANG_TURKISH = 123L
SAHPI_LANG_TSONGA = 124L
SAHPI_LANG_TATAR = 125L
SAHPI_LANG_TWI = 126L
SAHPI_LANG_UKRAINIAN = 127L
SAHPI_LANG_URDU = 128L
SAHPI_LANG_UZBEK = 129L
SAHPI_LANG_VIETNAMESE = 130L
SAHPI_LANG_VOLAPUK = 131L
SAHPI_LANG_WOLOF = 132L
SAHPI_LANG_XHOSA = 133L
SAHPI_LANG_YORUBA = 134L
SAHPI_LANG_CHINESE = 135L
SAHPI_LANG_ZULU = 136L
SAHPI_LANG_MAX_VALID = 136L
SAHPI_TL_TYPE_UNICODE = 0L
SAHPI_TL_TYPE_BCDPLUS = 1L
SAHPI_TL_TYPE_ASCII6 = 2L
SAHPI_TL_TYPE_TEXT = 3L
SAHPI_TL_TYPE_BINARY = 4L
SAHPI_TL_TYPE_MAX_VALID = 4L
SAHPI_ENT_UNSPECIFIED = 0L
SAHPI_ENT_OTHER = 1L
SAHPI_ENT_UNKNOWN = 2L
SAHPI_ENT_PROCESSOR = 3L
SAHPI_ENT_DISK_BAY = 4L
SAHPI_ENT_PERIPHERAL_BAY = 5L
SAHPI_ENT_SYS_MGMNT_MODULE = 6L
SAHPI_ENT_SYSTEM_BOARD = 7L
SAHPI_ENT_MEMORY_MODULE = 8L
SAHPI_ENT_PROCESSOR_MODULE = 9L
SAHPI_ENT_POWER_SUPPLY = 10L
SAHPI_ENT_ADD_IN_CARD = 11L
SAHPI_ENT_FRONT_PANEL_BOARD = 12L
SAHPI_ENT_BACK_PANEL_BOARD = 13L
SAHPI_ENT_POWER_SYSTEM_BOARD = 14L
SAHPI_ENT_DRIVE_BACKPLANE = 15L
SAHPI_ENT_SYS_EXPANSION_BOARD = 16L
SAHPI_ENT_OTHER_SYSTEM_BOARD = 17L
SAHPI_ENT_PROCESSOR_BOARD = 18L
SAHPI_ENT_POWER_UNIT = 19L
SAHPI_ENT_POWER_MODULE = 20L
SAHPI_ENT_POWER_MGMNT = 21L
SAHPI_ENT_CHASSIS_BACK_PANEL_BOARD = 22L
SAHPI_ENT_SYSTEM_CHASSIS = 23L
SAHPI_ENT_SUB_CHASSIS = 24L
SAHPI_ENT_OTHER_CHASSIS_BOARD = 25L
SAHPI_ENT_DISK_DRIVE_BAY = 26L
SAHPI_ENT_PERIPHERAL_BAY_2 = 27L
SAHPI_ENT_DEVICE_BAY = 28L
SAHPI_ENT_COOLING_DEVICE = 29L
SAHPI_ENT_COOLING_UNIT = 30L
SAHPI_ENT_INTERCONNECT = 31L
SAHPI_ENT_MEMORY_DEVICE = 32L
SAHPI_ENT_SYS_MGMNT_SOFTWARE = 33L
SAHPI_ENT_BIOS = 34L
SAHPI_ENT_OPERATING_SYSTEM = 35L
SAHPI_ENT_SYSTEM_BUS = 36L
SAHPI_ENT_GROUP = 37L
SAHPI_ENT_REMOTE = 38L
SAHPI_ENT_EXTERNAL_ENVIRONMENT = 39L
SAHPI_ENT_BATTERY = 40L
SAHPI_ENT_PROCESSING_BLADE = 41L
SAHPI_ENT_CONNECTIVITY_SWITCH = 42L
SAHPI_ENT_PROCESSOR_MEMORY_MODULE = 43L
SAHPI_ENT_IO_MODULE = 44L
SAHPI_ENT_PROCESSOR_IO_MODULE = 45L
SAHPI_ENT_MC_FIRMWARE = 46L
SAHPI_ENT_IPMI_CHANNEL = 47L
SAHPI_ENT_PCI_BUS = 48L
SAHPI_ENT_PCI_EXPRESS_BUS = 49L
SAHPI_ENT_SCSI_BUS = 50L
SAHPI_ENT_SATA_BUS = 51L
SAHPI_ENT_PROC_FSB = 52L
SAHPI_ENT_CLOCK = 53L
SAHPI_ENT_SYSTEM_FIRMWARE = 54L
SAHPI_ENT_CHASSIS_SPECIFIC = 144L
SAHPI_ENT_CHASSIS_SPECIFIC01 = 145L
SAHPI_ENT_CHASSIS_SPECIFIC02 = 146L
SAHPI_ENT_CHASSIS_SPECIFIC03 = 147L
SAHPI_ENT_CHASSIS_SPECIFIC04 = 148L
SAHPI_ENT_CHASSIS_SPECIFIC05 = 149L
SAHPI_ENT_CHASSIS_SPECIFIC06 = 150L
SAHPI_ENT_CHASSIS_SPECIFIC07 = 151L
SAHPI_ENT_CHASSIS_SPECIFIC08 = 152L
SAHPI_ENT_CHASSIS_SPECIFIC09 = 153L
SAHPI_ENT_CHASSIS_SPECIFIC10 = 154L
SAHPI_ENT_CHASSIS_SPECIFIC11 = 155L
SAHPI_ENT_CHASSIS_SPECIFIC12 = 156L
SAHPI_ENT_CHASSIS_SPECIFIC13 = 157L
SAHPI_ENT_BOARD_SET_SPECIFIC = 176L
SAHPI_ENT_OEM_SYSINT_SPECIFIC = 208L
SAHPI_ENT_ROOT = 65535L
SAHPI_ENT_RACK = 65536L
SAHPI_ENT_SUBRACK = 65537L
SAHPI_ENT_COMPACTPCI_CHASSIS = 65538L
SAHPI_ENT_ADVANCEDTCA_CHASSIS = 65539L
SAHPI_ENT_RACK_MOUNTED_SERVER = 65540L
SAHPI_ENT_SYSTEM_BLADE = 65541L
SAHPI_ENT_SWITCH = 65542L
SAHPI_ENT_SWITCH_BLADE = 65543L
SAHPI_ENT_SBC_BLADE = 65544L
SAHPI_ENT_IO_BLADE = 65545L
SAHPI_ENT_DISK_BLADE = 65546L
SAHPI_ENT_DISK_DRIVE = 65547L
SAHPI_ENT_FAN = 65548L
SAHPI_ENT_POWER_DISTRIBUTION_UNIT = 65549L
SAHPI_ENT_SPEC_PROC_BLADE = 65550L
SAHPI_ENT_IO_SUBBOARD = 65551L
SAHPI_ENT_SBC_SUBBOARD = 65552L
SAHPI_ENT_ALARM_MANAGER = 65553L
SAHPI_ENT_SHELF_MANAGER = 65554L
SAHPI_ENT_DISPLAY_PANEL = 65555L
SAHPI_ENT_SUBBOARD_CARRIER_BLADE = 65556L
SAHPI_ENT_PHYSICAL_SLOT = 65557L
SAHPI_ENT_PICMG_FRONT_BLADE = 65558L
SAHPI_ENT_SYSTEM_INVENTORY_DEVICE = 65559L
SAHPI_ENT_FILTRATION_UNIT = 65560L
SAHPI_ENT_AMC = 65561L
SAHPI_ENT_BMC = 65584L
SAHPI_ENT_IPMC = 65585L
SAHPI_ENT_MMC = 65586L
SAHPI_ENT_SHMC = 65587L
SAHPI_ENT_CPLD = 65588L
SAHPI_ENT_EPLD = 65589L
SAHPI_ENT_FPGA = 65590L
SAHPI_ENT_DASD = 65591L
SAHPI_ENT_NIC = 65592L
SAHPI_ENT_DSP = 65593L
SAHPI_ENT_UCODE = 65594L
SAHPI_ENT_NPU = 65595L
SAHPI_ENT_OEM = 65596L
SAHPI_ENT_INTERFACE = 65597L
SAHPI_ENT_MICROTCA_CHASSIS = 65598L
SAHPI_ENT_CARRIER = 65599L
SAHPI_ENT_CARRIER_MANAGER = 65600L
SAHPI_ENT_CONFIG_DATA = 65601L
SAHPI_ENT_INDICATOR = 65602L
SAHPI_ENT_MAX_VALID = 65602L
SAHPI_TEMPERATURE = 1L
SAHPI_VOLTAGE = 2L
SAHPI_CURRENT = 3L
SAHPI_FAN = 4L
SAHPI_PHYSICAL_SECURITY = 5L
SAHPI_PLATFORM_VIOLATION = 6L
SAHPI_PROCESSOR = 7L
SAHPI_POWER_SUPPLY = 8L
SAHPI_POWER_UNIT = 9L
SAHPI_COOLING_DEVICE = 10L
SAHPI_OTHER_UNITS_BASED_SENSOR = 11L
SAHPI_MEMORY = 12L
SAHPI_DRIVE_SLOT = 13L
SAHPI_POST_MEMORY_RESIZE = 14L
SAHPI_SYSTEM_FW_PROGRESS = 15L
SAHPI_EVENT_LOGGING_DISABLED = 16L
SAHPI_RESERVED1 = 17L
SAHPI_SYSTEM_EVENT = 18L
SAHPI_CRITICAL_INTERRUPT = 19L
SAHPI_BUTTON = 20L
SAHPI_MODULE_BOARD = 21L
SAHPI_MICROCONTROLLER_COPROCESSOR = 22L
SAHPI_ADDIN_CARD = 23L
SAHPI_CHASSIS = 24L
SAHPI_CHIP_SET = 25L
SAHPI_OTHER_FRU = 26L
SAHPI_CABLE_INTERCONNECT = 27L
SAHPI_TERMINATOR = 28L
SAHPI_SYSTEM_BOOT_INITIATED = 29L
SAHPI_BOOT_ERROR = 30L
SAHPI_OS_BOOT = 31L
SAHPI_OS_CRITICAL_STOP = 32L
SAHPI_SLOT_CONNECTOR = 33L
SAHPI_SYSTEM_ACPI_POWER_STATE = 34L
SAHPI_RESERVED2 = 35L
SAHPI_PLATFORM_ALERT = 36L
SAHPI_ENTITY_PRESENCE = 37L
SAHPI_MONITOR_ASIC_IC = 38L
SAHPI_LAN = 39L
SAHPI_MANAGEMENT_SUBSYSTEM_HEALTH = 40L
SAHPI_BATTERY = 41L
SAHPI_SESSION_AUDIT = 42L
SAHPI_VERSION_CHANGE = 43L
SAHPI_OPERATIONAL = 160L
SAHPI_OEM_SENSOR = 192L
SAHPI_COMM_CHANNEL_LINK_STATE = 65537L
SAHPI_MANAGEMENT_BUS_STATE = 65538L
SAHPI_COMM_CHANNEL_BUS_STATE = 65539L
SAHPI_CONFIG_DATA = 65540L
SAHPI_POWER_BUDGET = 65541L
SAHPI_SENSOR_TYPE_MAX_VALID = 65541L
SAHPI_SENSOR_READING_TYPE_INT64 = 0L
SAHPI_SENSOR_READING_TYPE_UINT64 = 1L
SAHPI_SENSOR_READING_TYPE_FLOAT64 = 2L
SAHPI_SENSOR_READING_TYPE_BUFFER = 3L
SAHPI_SENSOR_READING_TYPE_MAX_VALID = 3L
SAHPI_SENS_ADD_EVENTS_TO_MASKS = 0L
SAHPI_SENS_REMOVE_EVENTS_FROM_MASKS = 1L
SAHPI_SENS_EVENT_MASK_ACTION_MAX_VALID = 1L
SAHPI_SU_UNSPECIFIED = 0L
SAHPI_SU_DEGREES_C = 1L
SAHPI_SU_DEGREES_F = 2L
SAHPI_SU_DEGREES_K = 3L
SAHPI_SU_VOLTS = 4L
SAHPI_SU_AMPS = 5L
SAHPI_SU_WATTS = 6L
SAHPI_SU_JOULES = 7L
SAHPI_SU_COULOMBS = 8L
SAHPI_SU_VA = 9L
SAHPI_SU_NITS = 10L
SAHPI_SU_LUMEN = 11L
SAHPI_SU_LUX = 12L
SAHPI_SU_CANDELA = 13L
SAHPI_SU_KPA = 14L
SAHPI_SU_PSI = 15L
SAHPI_SU_NEWTON = 16L
SAHPI_SU_CFM = 17L
SAHPI_SU_RPM = 18L
SAHPI_SU_HZ = 19L
SAHPI_SU_MICROSECOND = 20L
SAHPI_SU_MILLISECOND = 21L
SAHPI_SU_SECOND = 22L
SAHPI_SU_MINUTE = 23L
SAHPI_SU_HOUR = 24L
SAHPI_SU_DAY = 25L
SAHPI_SU_WEEK = 26L
SAHPI_SU_MIL = 27L
SAHPI_SU_INCHES = 28L
SAHPI_SU_FEET = 29L
SAHPI_SU_CU_IN = 30L
SAHPI_SU_CU_FEET = 31L
SAHPI_SU_MM = 32L
SAHPI_SU_CM = 33L
SAHPI_SU_M = 34L
SAHPI_SU_CU_CM = 35L
SAHPI_SU_CU_M = 36L
SAHPI_SU_LITERS = 37L
SAHPI_SU_FLUID_OUNCE = 38L
SAHPI_SU_RADIANS = 39L
SAHPI_SU_STERADIANS = 40L
SAHPI_SU_REVOLUTIONS = 41L
SAHPI_SU_CYCLES = 42L
SAHPI_SU_GRAVITIES = 43L
SAHPI_SU_OUNCE = 44L
SAHPI_SU_POUND = 45L
SAHPI_SU_FT_LB = 46L
SAHPI_SU_OZ_IN = 47L
SAHPI_SU_GAUSS = 48L
SAHPI_SU_GILBERTS = 49L
SAHPI_SU_HENRY = 50L
SAHPI_SU_MILLIHENRY = 51L
SAHPI_SU_FARAD = 52L
SAHPI_SU_MICROFARAD = 53L
SAHPI_SU_OHMS = 54L
SAHPI_SU_SIEMENS = 55L
SAHPI_SU_MOLE = 56L
SAHPI_SU_BECQUEREL = 57L
SAHPI_SU_PPM = 58L
SAHPI_SU_RESERVED = 59L
SAHPI_SU_DECIBELS = 60L
SAHPI_SU_DBA = 61L
SAHPI_SU_DBC = 62L
SAHPI_SU_GRAY = 63L
SAHPI_SU_SIEVERT = 64L
SAHPI_SU_COLOR_TEMP_DEG_K = 65L
SAHPI_SU_BIT = 66L
SAHPI_SU_KILOBIT = 67L
SAHPI_SU_MEGABIT = 68L
SAHPI_SU_GIGABIT = 69L
SAHPI_SU_BYTE = 70L
SAHPI_SU_KILOBYTE = 71L
SAHPI_SU_MEGABYTE = 72L
SAHPI_SU_GIGABYTE = 73L
SAHPI_SU_WORD = 74L
SAHPI_SU_DWORD = 75L
SAHPI_SU_QWORD = 76L
SAHPI_SU_LINE = 77L
SAHPI_SU_HIT = 78L
SAHPI_SU_MISS = 79L
SAHPI_SU_RETRY = 80L
SAHPI_SU_RESET = 81L
SAHPI_SU_OVERRUN = 82L
SAHPI_SU_UNDERRUN = 83L
SAHPI_SU_COLLISION = 84L
SAHPI_SU_PACKETS = 85L
SAHPI_SU_MESSAGES = 86L
SAHPI_SU_CHARACTERS = 87L
SAHPI_SU_ERRORS = 88L
SAHPI_SU_CORRECTABLE_ERRORS = 89L
SAHPI_SU_UNCORRECTABLE_ERRORS = 90L
SAHPI_SU_MAX_VALID = 90L
SAHPI_SMUU_NONE = 0L
SAHPI_SMUU_BASIC_OVER_MODIFIER = 1L
SAHPI_SMUU_BASIC_TIMES_MODIFIER = 2L
SAHPI_SMUU_MAX_VALID = 2L
SAHPI_SEC_PER_EVENT = 0L
SAHPI_SEC_READ_ONLY_MASKS = 1L
SAHPI_SEC_READ_ONLY = 2L
SAHPI_SEC_MAX_VALID = 2L
SAHPI_CTRL_TYPE_DIGITAL = 0L
SAHPI_CTRL_TYPE_DISCRETE = 1L
SAHPI_CTRL_TYPE_ANALOG = 2L
SAHPI_CTRL_TYPE_STREAM = 3L
SAHPI_CTRL_TYPE_TEXT = 4L
SAHPI_CTRL_TYPE_OEM = 192L
SAHPI_CTRL_TYPE_MAX_VALID = 192L
SAHPI_CTRL_STATE_OFF = 0L
SAHPI_CTRL_STATE_ON = 1L
SAHPI_CTRL_STATE_PULSE_OFF = 2L
SAHPI_CTRL_STATE_PULSE_ON = 3L
SAHPI_CTRL_STATE_MAX_VALID = 3L
SAHPI_CTRL_MODE_AUTO = 0L
SAHPI_CTRL_MODE_MANUAL = 1L
SAHPI_CTRL_MODE_MAX_VALID = 1L
SAHPI_CTRL_GENERIC = 0L
SAHPI_CTRL_LED = 1L
SAHPI_CTRL_FAN_SPEED = 2L
SAHPI_CTRL_DRY_CONTACT_CLOSURE = 3L
SAHPI_CTRL_POWER_SUPPLY_INHIBIT = 4L
SAHPI_CTRL_AUDIBLE = 5L
SAHPI_CTRL_FRONT_PANEL_LOCKOUT = 6L
SAHPI_CTRL_POWER_INTERLOCK = 7L
SAHPI_CTRL_POWER_STATE = 8L
SAHPI_CTRL_LCD_DISPLAY = 9L
SAHPI_CTRL_OEM = 10L
SAHPI_CTRL_GENERIC_ADDRESS = 11L
SAHPI_CTRL_IP_ADDRESS = 12L
SAHPI_CTRL_RESOURCE_ID = 13L
SAHPI_CTRL_POWER_BUDGET = 14L
SAHPI_CTRL_ACTIVATE = 15L
SAHPI_CTRL_RESET = 16L
SAHPI_CTRL_OUTPUT_TYPE_MAX_VALID = 16L
SAHPI_IDR_AREATYPE_INTERNAL_USE = 176L
SAHPI_IDR_AREATYPE_CHASSIS_INFO = 177L
SAHPI_IDR_AREATYPE_BOARD_INFO = 178L
SAHPI_IDR_AREATYPE_PRODUCT_INFO = 179L
SAHPI_IDR_AREATYPE_OEM = 192L
SAHPI_IDR_AREATYPE_UNSPECIFIED = 255L
SAHPI_IDR_AREATYPE_MAX_VALID = 255L
SAHPI_IDR_FIELDTYPE_CHASSIS_TYPE = 0L
SAHPI_IDR_FIELDTYPE_MFG_DATETIME = 1L
SAHPI_IDR_FIELDTYPE_MANUFACTURER = 2L
SAHPI_IDR_FIELDTYPE_PRODUCT_NAME = 3L
SAHPI_IDR_FIELDTYPE_PRODUCT_VERSION = 4L
SAHPI_IDR_FIELDTYPE_SERIAL_NUMBER = 5L
SAHPI_IDR_FIELDTYPE_PART_NUMBER = 6L
SAHPI_IDR_FIELDTYPE_FILE_ID = 7L
SAHPI_IDR_FIELDTYPE_ASSET_TAG = 8L
SAHPI_IDR_FIELDTYPE_CUSTOM = 9L
SAHPI_IDR_FIELDTYPE_UNSPECIFIED = 255L
SAHPI_IDR_FIELDTYPE_MAX_VALID = 255L
SAHPI_WA_NO_ACTION = 0L
SAHPI_WA_RESET = 1L
SAHPI_WA_POWER_DOWN = 2L
SAHPI_WA_POWER_CYCLE = 3L
SAHPI_WA_MAX_VALID = 3L
SAHPI_WAE_NO_ACTION = 0L
SAHPI_WAE_RESET = 1L
SAHPI_WAE_POWER_DOWN = 2L
SAHPI_WAE_POWER_CYCLE = 3L
SAHPI_WAE_TIMER_INT = 8L
SAHPI_WAE_MAX_VALID = 8L
SAHPI_WPI_NONE = 0L
SAHPI_WPI_SMI = 1L
SAHPI_WPI_NMI = 2L
SAHPI_WPI_MESSAGE_INTERRUPT = 3L
SAHPI_WPI_OEM = 15L
SAHPI_WPI_MAX_VALID = 15L
SAHPI_WTU_NONE = 0L
SAHPI_WTU_BIOS_FRB2 = 1L
SAHPI_WTU_BIOS_POST = 2L
SAHPI_WTU_OS_LOAD = 3L
SAHPI_WTU_SMS_OS = 4L
SAHPI_WTU_OEM = 5L
SAHPI_WTU_UNSPECIFIED = 15L
SAHPI_WTU_MAX_VALID = 15L
SAHPI_DIMITEST_NONDEGRADING = 0L
SAHPI_DIMITEST_DEGRADING = 1L
SAHPI_DIMITEST_VENDOR_DEFINED_LEVEL = 2L
SAHPI_DIMITEST_SERVICE_IMPACT_MAX_VALID = 2L
SAHPI_DIMITEST_STATUS_NOT_RUN = 0L
SAHPI_DIMITEST_STATUS_FINISHED_NO_ERRORS = 1L
SAHPI_DIMITEST_STATUS_FINISHED_ERRORS = 2L
SAHPI_DIMITEST_STATUS_CANCELED = 3L
SAHPI_DIMITEST_STATUS_RUNNING = 4L
SAHPI_DIMITEST_STATUS_MAX_VALID = 4L
SAHPI_DIMITEST_STATUSERR_NOERR = 0L
SAHPI_DIMITEST_STATUSERR_RUNERR = 1L
SAHPI_DIMITEST_STATUSERR_UNDEF = 2L
SAHPI_DIMITEST_STATUSERR_MAX_VALID = 2L
SAHPI_DIMITEST_PARAM_TYPE_BOOLEAN = 0L
SAHPI_DIMITEST_PARAM_TYPE_INT32 = 1L
SAHPI_DIMITEST_PARAM_TYPE_FLOAT64 = 2L
SAHPI_DIMITEST_PARAM_TYPE_TEXT = 3L
SAHPI_DIMITEST_PARAM_TYPE_MAX_VALID = 3L
SAHPI_DIMI_READY = 0L
SAHPI_DIMI_WRONG_STATE = 1L
SAHPI_DIMI_BUSY = 2L
SAHPI_DIMI_READY_MAX_VALID = 2L
SAHPI_FUMI_SPEC_INFO_NONE = 0L
SAHPI_FUMI_SPEC_INFO_SAF_DEFINED = 1L
SAHPI_FUMI_SPEC_INFO_OEM_DEFINED = 2L
SAHPI_FUMI_SPEC_INFO_MAX_VALID = 2L
SAHPI_FUMI_SPEC_HPM1 = 0L
SAHPI_FUMI_SPEC_MAX_VALID = 0L
SAHPI_FUMI_PROCESS_NONDEGRADING = 0L
SAHPI_FUMI_PROCESS_DEGRADING = 1L
SAHPI_FUMI_PROCESS_VENDOR_DEFINED_IMPACT_LEVEL = 2L
SAHPI_FUMI_PROCESS_IMPACT_MAX_VALID = 2L
SAHPI_FUMI_SRC_VALID = 0L
SAHPI_FUMI_SRC_PROTOCOL_NOT_SUPPORTED = 1L
SAHPI_FUMI_SRC_UNREACHABLE = 2L
SAHPI_FUMI_SRC_VALIDATION_NOT_STARTED = 3L
SAHPI_FUMI_SRC_VALIDATION_INITIATED = 4L
SAHPI_FUMI_SRC_VALIDATION_FAIL = 5L
SAHPI_FUMI_SRC_TYPE_MISMATCH = 6L
SAHPI_FUMI_SRC_INVALID = 7L
SAHPI_FUMI_SRC_VALIDITY_UNKNOWN = 8L
SAHPI_FUMI_SRC_STATUS_MAX_VALID = 8L
SAHPI_FUMI_BANK_VALID = 0L
SAHPI_FUMI_BANK_UPGRADE_IN_PROGRESS = 1L
SAHPI_FUMI_BANK_CORRUPTED = 2L
SAHPI_FUMI_BANK_ACTIVE = 3L
SAHPI_FUMI_BANK_BUSY = 4L
SAHPI_FUMI_BANK_UNKNOWN = 5L
SAHPI_FUMI_BANK_STATE_MAX_VALID = 5L
SAHPI_FUMI_OPERATION_NOTSTARTED = 0L
SAHPI_FUMI_SOURCE_VALIDATION_INITIATED = 1L
SAHPI_FUMI_SOURCE_VALIDATION_FAILED = 2L
SAHPI_FUMI_SOURCE_VALIDATION_DONE = 3L
SAHPI_FUMI_SOURCE_VALIDATION_CANCELLED = 4L
SAHPI_FUMI_INSTALL_INITIATED = 5L
SAHPI_FUMI_INSTALL_FAILED_ROLLBACK_NEEDED = 6L
SAHPI_FUMI_INSTALL_FAILED_ROLLBACK_INITIATED = 7L
SAHPI_FUMI_INSTALL_FAILED_ROLLBACK_NOT_POSSIBLE = 8L
SAHPI_FUMI_INSTALL_DONE = 9L
SAHPI_FUMI_INSTALL_CANCELLED = 10L
SAHPI_FUMI_ROLLBACK_INITIATED = 11L
SAHPI_FUMI_ROLLBACK_FAILED = 12L
SAHPI_FUMI_ROLLBACK_DONE = 13L
SAHPI_FUMI_ROLLBACK_CANCELLED = 14L
SAHPI_FUMI_BACKUP_INITIATED = 15L
SAHPI_FUMI_BACKUP_FAILED = 16L
SAHPI_FUMI_BACKUP_DONE = 17L
SAHPI_FUMI_BACKUP_CANCELLED = 18L
SAHPI_FUMI_BANK_COPY_INITIATED = 19L
SAHPI_FUMI_BANK_COPY_FAILED = 20L
SAHPI_FUMI_BANK_COPY_DONE = 21L
SAHPI_FUMI_BANK_COPY_CANCELLED = 22L
SAHPI_FUMI_TARGET_VERIFY_INITIATED = 23L
SAHPI_FUMI_TARGET_VERIFY_FAILED = 24L
SAHPI_FUMI_TARGET_VERIFY_DONE = 25L
SAHPI_FUMI_TARGET_VERIFY_CANCELLED = 26L
SAHPI_FUMI_ACTIVATE_INITIATED = 27L
SAHPI_FUMI_ACTIVATE_FAILED_ROLLBACK_NEEDED = 28L
SAHPI_FUMI_ACTIVATE_FAILED_ROLLBACK_INITIATED = 29L
SAHPI_FUMI_ACTIVATE_FAILED_ROLLBACK_NOT_POSSIBLE = 30L
SAHPI_FUMI_ACTIVATE_DONE = 31L
SAHPI_FUMI_ACTIVATE_CANCELLED = 32L
SAHPI_FUMI_UPGRADE_STATUS_MAX_VALID = 32L
SAHPI_HS_INDICATOR_OFF = 0L
SAHPI_HS_INDICATOR_ON = 1L
SAHPI_HS_INDICATOR_STATE_MAX_VALID = 1L
SAHPI_HS_ACTION_INSERTION = 0L
SAHPI_HS_ACTION_EXTRACTION = 1L
SAHPI_HS_ACTION_MAX_VALID = 1L
SAHPI_HS_STATE_INACTIVE = 0L
SAHPI_HS_STATE_INSERTION_PENDING = 1L
SAHPI_HS_STATE_ACTIVE = 2L
SAHPI_HS_STATE_EXTRACTION_PENDING = 3L
SAHPI_HS_STATE_NOT_PRESENT = 4L
SAHPI_HS_STATE_MAX_VALID = 4L
SAHPI_HS_CAUSE_AUTO_POLICY = 0L
SAHPI_HS_CAUSE_EXT_SOFTWARE = 1L
SAHPI_HS_CAUSE_OPERATOR_INIT = 2L
SAHPI_HS_CAUSE_USER_UPDATE = 3L
SAHPI_HS_CAUSE_UNEXPECTED_DEACTIVATION = 4L
SAHPI_HS_CAUSE_SURPRISE_EXTRACTION = 5L
SAHPI_HS_CAUSE_EXTRACTION_UPDATE = 6L
SAHPI_HS_CAUSE_HARDWARE_FAULT = 7L
SAHPI_HS_CAUSE_CONTAINING_FRU = 8L
SAHPI_HS_CAUSE_UNKNOWN = 65535L
SAHPI_HS_CAUSE_MAX_VALID = 65535L
SAHPI_CRITICAL = 0L
SAHPI_MAJOR = 1L
SAHPI_MINOR = 2L
SAHPI_INFORMATIONAL = 3L
SAHPI_OK = 4L
SAHPI_DEBUG = 240L
SAHPI_ALL_SEVERITIES = 255L
SAHPI_SEVERITY_MAX_VALID = 240L
SAHPI_RESE_RESOURCE_FAILURE = 0L
SAHPI_RESE_RESOURCE_RESTORED = 1L
SAHPI_RESE_RESOURCE_ADDED = 2L
SAHPI_RESE_RESOURCE_REMOVED = 3L
SAHPI_RESE_RESOURCE_INACCESSIBLE = 4L
SAHPI_RESE_RESOURCE_UPDATED = 5L
SAHPI_RESE_TYPE_MAX_VALID = 5L
SAHPI_DOMAIN_REF_ADDED = 0L
SAHPI_DOMAIN_REF_REMOVED = 1L
SAHPI_DOMAIN_EVENT_TYPE_MAX_VALID = 1L
SAHPI_HPIE_AUDIT = 0L
SAHPI_HPIE_STARTUP = 1L
SAHPI_HPIE_OTHER = 2L
SAHPI_HPIE_TYPE_MAX_VALID = 2L
SAHPI_ET_RESOURCE = 0L
SAHPI_ET_DOMAIN = 1L
SAHPI_ET_SENSOR = 2L
SAHPI_ET_SENSOR_ENABLE_CHANGE = 3L
SAHPI_ET_HOTSWAP = 4L
SAHPI_ET_WATCHDOG = 5L
SAHPI_ET_HPI_SW = 6L
SAHPI_ET_OEM = 7L
SAHPI_ET_USER = 8L
SAHPI_ET_DIMI = 9L
SAHPI_ET_DIMI_UPDATE = 10L
SAHPI_ET_FUMI = 11L
SAHPI_ET_MAX_VALID = 11L
SAHPI_STATUS_COND_TYPE_SENSOR = 0L
SAHPI_STATUS_COND_TYPE_RESOURCE = 1L
SAHPI_STATUS_COND_TYPE_OEM = 2L
SAHPI_STATUS_COND_TYPE_USER = 3L
SAHPI_STATUS_COND_TYPE_MAX_VALID = 3L
SAHPI_ANNUNCIATOR_MODE_AUTO = 0L
SAHPI_ANNUNCIATOR_MODE_USER = 1L
SAHPI_ANNUNCIATOR_MODE_SHARED = 2L
SAHPI_ANNUNCIATOR_MODE_MAX_VALID = 2L
SAHPI_ANNUNCIATOR_TYPE_LED = 0L
SAHPI_ANNUNCIATOR_TYPE_DRY_CONTACT_CLOSURE = 1L
SAHPI_ANNUNCIATOR_TYPE_AUDIBLE = 2L
SAHPI_ANNUNCIATOR_TYPE_LCD_DISPLAY = 3L
SAHPI_ANNUNCIATOR_TYPE_MESSAGE = 4L
SAHPI_ANNUNCIATOR_TYPE_COMPOSITE = 5L
SAHPI_ANNUNCIATOR_TYPE_OEM = 6L
SAHPI_ANNUNCIATOR_TYPE_MAX_VALID = 6L
SAHPI_NO_RECORD = 0L
SAHPI_CTRL_RDR = 1L
SAHPI_SENSOR_RDR = 2L
SAHPI_INVENTORY_RDR = 3L
SAHPI_WATCHDOG_RDR = 4L
SAHPI_ANNUNCIATOR_RDR = 5L
SAHPI_DIMI_RDR = 6L
SAHPI_FUMI_RDR = 7L
SAHPI_RDR_TYPE_MAX_VALID = 7L
SAHPI_DEFAULT_PARM = 0L
SAHPI_SAVE_PARM = 1L
SAHPI_RESTORE_PARM = 2L
SAHPI_PARM_ACTION_MAX_VALID = 2L
SAHPI_COLD_RESET = 0L
SAHPI_WARM_RESET = 1L
SAHPI_RESET_ASSERT = 2L
SAHPI_RESET_DEASSERT = 3L
SAHPI_RESET_MAX_VALID = 3L
SAHPI_POWER_OFF = 0L
SAHPI_POWER_ON = 1L
SAHPI_POWER_CYCLE = 2L
SAHPI_POWER_STATE_MAX_VALID = 2L
SAHPI_EL_OVERFLOW_DROP = 0L
SAHPI_EL_OVERFLOW_OVERWRITE = 1L
SAHPI_EL_OVERFLOW_ACTION_MAX_TYPE = 1L
ATCAHPI_LED_COLOR_RESERVED = 0L
ATCAHPI_LED_COLOR_BLUE = 1L
ATCAHPI_LED_COLOR_RED = 2L
ATCAHPI_LED_COLOR_GREEN = 3L
ATCAHPI_LED_COLOR_AMBER = 4L
ATCAHPI_LED_COLOR_ORANGE = 5L
ATCAHPI_LED_COLOR_WHITE = 6L
ATCAHPI_LED_COLOR_NO_CHANGE = 14L
ATCAHPI_LED_COLOR_USE_DEFAULT = 15L
ATCAHPI_LED_AUTO = 0L
ATCAHPI_LED_MANUAL = 1L
ATCAHPI_LED_LAMP_TEST = 2L
ATCAHPI_LED_BR_SUPPORTED = 0L
ATCAHPI_LED_BR_NOT_SUPPORTED = 1L
ATCAHPI_LED_BR_UNKNOWN = 2L
XTCAHPI_LED_COLOR_RESERVED = 0L
XTCAHPI_LED_COLOR_BLUE = 1L
XTCAHPI_LED_COLOR_RED = 2L
XTCAHPI_LED_COLOR_GREEN = 3L
XTCAHPI_LED_COLOR_AMBER = 4L
XTCAHPI_LED_COLOR_ORANGE = 5L
XTCAHPI_LED_COLOR_WHITE = 6L
XTCAHPI_LED_COLOR_NO_CHANGE = 14L
XTCAHPI_LED_COLOR_USE_DEFAULT = 15L
XTCAHPI_LED_AUTO = 0L
XTCAHPI_LED_MANUAL = 1L
XTCAHPI_LED_LAMP_TEST = 2L
XTCAHPI_LED_BR_SUPPORTED = 0L
XTCAHPI_LED_BR_NOT_SUPPORTED = 1L
XTCAHPI_LED_BR_UNKNOWN = 2L
SA_ERR_HPI_OK = 0L

#**********************************************************
#* HPI Complex Data Types
#**********************************************************
#**
# HPI struct SaHpiTextBufferT
#**
class SaHpiTextBufferT:
    def __init__( self ):
        # SaHpiTextTypeT
        self.DataType = None
        # SaHpiLanguageT
        self.Language = None
        # SaHpiUint8T
        self.DataLength = None
        # SaHpiUint8T[SAHPI_MAX_TEXT_BUFFER_LENGTH]
        self.Data = None

#**
# HPI struct SaHpiEntityT
#**
class SaHpiEntityT:
    def __init__( self ):
        # SaHpiEntityTypeT
        self.EntityType = None
        # SaHpiEntityLocationT
        self.EntityLocation = None

#**
# HPI struct SaHpiEntityPathT
#**
class SaHpiEntityPathT:
    def __init__( self ):
        # SaHpiEntityT[SAHPI_MAX_ENTITY_PATH]
        self.Entry = None

#**
# HPI union SaHpiSensorReadingUnionT
#**
class SaHpiSensorReadingUnionT:
    def __init__( self ):
        # SaHpiInt64T
        self.SensorInt64 = None
        # SaHpiUint64T
        self.SensorUint64 = None
        # SaHpiFloat64T
        self.SensorFloat64 = None
        # SaHpiUint8T[SAHPI_SENSOR_BUFFER_LENGTH]
        self.SensorBuffer = None

#**
# HPI struct SaHpiSensorReadingT
#**
class SaHpiSensorReadingT:
    def __init__( self ):
        # SaHpiBoolT
        self.IsSupported = None
        # SaHpiSensorReadingTypeT
        self.Type = None
        # HPI union SaHpiSensorReadingUnionT
        self.Value = None

#**
# HPI struct SaHpiSensorThresholdsT
#**
class SaHpiSensorThresholdsT:
    def __init__( self ):
        # HPI struct SaHpiSensorReadingT
        self.LowCritical = None
        # HPI struct SaHpiSensorReadingT
        self.LowMajor = None
        # HPI struct SaHpiSensorReadingT
        self.LowMinor = None
        # HPI struct SaHpiSensorReadingT
        self.UpCritical = None
        # HPI struct SaHpiSensorReadingT
        self.UpMajor = None
        # HPI struct SaHpiSensorReadingT
        self.UpMinor = None
        # HPI struct SaHpiSensorReadingT
        self.PosThdHysteresis = None
        # HPI struct SaHpiSensorReadingT
        self.NegThdHysteresis = None

#**
# HPI struct SaHpiSensorRangeT
#**
class SaHpiSensorRangeT:
    def __init__( self ):
        # SaHpiSensorRangeFlagsT
        self.Flags = None
        # HPI struct SaHpiSensorReadingT
        self.Max = None
        # HPI struct SaHpiSensorReadingT
        self.Min = None
        # HPI struct SaHpiSensorReadingT
        self.Nominal = None
        # HPI struct SaHpiSensorReadingT
        self.NormalMax = None
        # HPI struct SaHpiSensorReadingT
        self.NormalMin = None

#**
# HPI struct SaHpiSensorDataFormatT
#**
class SaHpiSensorDataFormatT:
    def __init__( self ):
        # SaHpiBoolT
        self.IsSupported = None
        # SaHpiSensorReadingTypeT
        self.ReadingType = None
        # SaHpiSensorUnitsT
        self.BaseUnits = None
        # SaHpiSensorUnitsT
        self.ModifierUnits = None
        # SaHpiSensorModUnitUseT
        self.ModifierUse = None
        # SaHpiBoolT
        self.Percentage = None
        # HPI struct SaHpiSensorRangeT
        self.Range = None
        # SaHpiFloat64T
        self.AccuracyFactor = None

#**
# HPI struct SaHpiSensorThdDefnT
#**
class SaHpiSensorThdDefnT:
    def __init__( self ):
        # SaHpiBoolT
        self.IsAccessible = None
        # SaHpiSensorThdMaskT
        self.ReadThold = None
        # SaHpiSensorThdMaskT
        self.WriteThold = None
        # SaHpiBoolT
        self.Nonlinear = None

#**
# HPI struct SaHpiSensorRecT
#**
class SaHpiSensorRecT:
    def __init__( self ):
        # SaHpiSensorNumT
        self.Num = None
        # SaHpiSensorTypeT
        self.Type = None
        # SaHpiEventCategoryT
        self.Category = None
        # SaHpiBoolT
        self.EnableCtrl = None
        # SaHpiSensorEventCtrlT
        self.EventCtrl = None
        # SaHpiEventStateT
        self.Events = None
        # HPI struct SaHpiSensorDataFormatT
        self.DataFormat = None
        # HPI struct SaHpiSensorThdDefnT
        self.ThresholdDefn = None
        # SaHpiUint32T
        self.Oem = None

#**
# HPI struct SaHpiCtrlStateStreamT
#**
class SaHpiCtrlStateStreamT:
    def __init__( self ):
        # SaHpiBoolT
        self.Repeat = None
        # SaHpiUint32T
        self.StreamLength = None
        # SaHpiUint8T[SAHPI_CTRL_MAX_STREAM_LENGTH]
        self.Stream = None

#**
# HPI struct SaHpiCtrlStateTextT
#**
class SaHpiCtrlStateTextT:
    def __init__( self ):
        # SaHpiTxtLineNumT
        self.Line = None
        # HPI struct SaHpiTextBufferT
        self.Text = None

#**
# HPI struct SaHpiCtrlStateOemT
#**
class SaHpiCtrlStateOemT:
    def __init__( self ):
        # SaHpiManufacturerIdT
        self.MId = None
        # SaHpiUint8T
        self.BodyLength = None
        # SaHpiUint8T[SAHPI_CTRL_MAX_OEM_BODY_LENGTH]
        self.Body = None

#**
# HPI union SaHpiCtrlStateUnionT
#**
class SaHpiCtrlStateUnionT:
    def __init__( self ):
        # SaHpiCtrlStateDigitalT
        self.Digital = None
        # SaHpiCtrlStateDiscreteT
        self.Discrete = None
        # SaHpiCtrlStateAnalogT
        self.Analog = None
        # HPI struct SaHpiCtrlStateStreamT
        self.Stream = None
        # HPI struct SaHpiCtrlStateTextT
        self.Text = None
        # HPI struct SaHpiCtrlStateOemT
        self.Oem = None

#**
# HPI struct SaHpiCtrlStateT
#**
class SaHpiCtrlStateT:
    def __init__( self ):
        # SaHpiCtrlTypeT
        self.Type = None
        # HPI union SaHpiCtrlStateUnionT
        self.StateUnion = None

#**
# HPI struct SaHpiCtrlRecDigitalT
#**
class SaHpiCtrlRecDigitalT:
    def __init__( self ):
        # SaHpiCtrlStateDigitalT
        self.Default = None

#**
# HPI struct SaHpiCtrlRecDiscreteT
#**
class SaHpiCtrlRecDiscreteT:
    def __init__( self ):
        # SaHpiCtrlStateDiscreteT
        self.Default = None

#**
# HPI struct SaHpiCtrlRecAnalogT
#**
class SaHpiCtrlRecAnalogT:
    def __init__( self ):
        # SaHpiCtrlStateAnalogT
        self.Min = None
        # SaHpiCtrlStateAnalogT
        self.Max = None
        # SaHpiCtrlStateAnalogT
        self.Default = None

#**
# HPI struct SaHpiCtrlRecStreamT
#**
class SaHpiCtrlRecStreamT:
    def __init__( self ):
        # HPI struct SaHpiCtrlStateStreamT
        self.Default = None

#**
# HPI struct SaHpiCtrlRecTextT
#**
class SaHpiCtrlRecTextT:
    def __init__( self ):
        # SaHpiUint8T
        self.MaxChars = None
        # SaHpiUint8T
        self.MaxLines = None
        # SaHpiLanguageT
        self.Language = None
        # SaHpiTextTypeT
        self.DataType = None
        # HPI struct SaHpiCtrlStateTextT
        self.Default = None

#**
# HPI struct SaHpiCtrlRecOemT
#**
class SaHpiCtrlRecOemT:
    def __init__( self ):
        # SaHpiManufacturerIdT
        self.MId = None
        # SaHpiUint8T[SAHPI_CTRL_OEM_CONFIG_LENGTH]
        self.ConfigData = None
        # HPI struct SaHpiCtrlStateOemT
        self.Default = None

#**
# HPI union SaHpiCtrlRecUnionT
#**
class SaHpiCtrlRecUnionT:
    def __init__( self ):
        # HPI struct SaHpiCtrlRecDigitalT
        self.Digital = None
        # HPI struct SaHpiCtrlRecDiscreteT
        self.Discrete = None
        # HPI struct SaHpiCtrlRecAnalogT
        self.Analog = None
        # HPI struct SaHpiCtrlRecStreamT
        self.Stream = None
        # HPI struct SaHpiCtrlRecTextT
        self.Text = None
        # HPI struct SaHpiCtrlRecOemT
        self.Oem = None

#**
# HPI struct SaHpiCtrlDefaultModeT
#**
class SaHpiCtrlDefaultModeT:
    def __init__( self ):
        # SaHpiCtrlModeT
        self.Mode = None
        # SaHpiBoolT
        self.ReadOnly = None

#**
# HPI struct SaHpiCtrlRecT
#**
class SaHpiCtrlRecT:
    def __init__( self ):
        # SaHpiCtrlNumT
        self.Num = None
        # SaHpiCtrlOutputTypeT
        self.OutputType = None
        # SaHpiCtrlTypeT
        self.Type = None
        # HPI union SaHpiCtrlRecUnionT
        self.TypeUnion = None
        # HPI struct SaHpiCtrlDefaultModeT
        self.DefaultMode = None
        # SaHpiBoolT
        self.WriteOnly = None
        # SaHpiUint32T
        self.Oem = None

#**
# HPI struct SaHpiIdrFieldT
#**
class SaHpiIdrFieldT:
    def __init__( self ):
        # SaHpiEntryIdT
        self.AreaId = None
        # SaHpiEntryIdT
        self.FieldId = None
        # SaHpiIdrFieldTypeT
        self.Type = None
        # SaHpiBoolT
        self.ReadOnly = None
        # HPI struct SaHpiTextBufferT
        self.Field = None

#**
# HPI struct SaHpiIdrAreaHeaderT
#**
class SaHpiIdrAreaHeaderT:
    def __init__( self ):
        # SaHpiEntryIdT
        self.AreaId = None
        # SaHpiIdrAreaTypeT
        self.Type = None
        # SaHpiBoolT
        self.ReadOnly = None
        # SaHpiUint32T
        self.NumFields = None

#**
# HPI struct SaHpiIdrInfoT
#**
class SaHpiIdrInfoT:
    def __init__( self ):
        # SaHpiIdrIdT
        self.IdrId = None
        # SaHpiUint32T
        self.UpdateCount = None
        # SaHpiBoolT
        self.ReadOnly = None
        # SaHpiUint32T
        self.NumAreas = None

#**
# HPI struct SaHpiInventoryRecT
#**
class SaHpiInventoryRecT:
    def __init__( self ):
        # SaHpiIdrIdT
        self.IdrId = None
        # SaHpiBoolT
        self.Persistent = None
        # SaHpiUint32T
        self.Oem = None

#**
# HPI struct SaHpiWatchdogT
#**
class SaHpiWatchdogT:
    def __init__( self ):
        # SaHpiBoolT
        self.Log = None
        # SaHpiBoolT
        self.Running = None
        # SaHpiWatchdogTimerUseT
        self.TimerUse = None
        # SaHpiWatchdogActionT
        self.TimerAction = None
        # SaHpiWatchdogPretimerInterruptT
        self.PretimerInterrupt = None
        # SaHpiUint32T
        self.PreTimeoutInterval = None
        # SaHpiWatchdogExpFlagsT
        self.TimerUseExpFlags = None
        # SaHpiUint32T
        self.InitialCount = None
        # SaHpiUint32T
        self.PresentCount = None

#**
# HPI struct SaHpiWatchdogRecT
#**
class SaHpiWatchdogRecT:
    def __init__( self ):
        # SaHpiWatchdogNumT
        self.WatchdogNum = None
        # SaHpiUint32T
        self.Oem = None

#**
# HPI struct SaHpiDimiTestAffectedEntityT
#**
class SaHpiDimiTestAffectedEntityT:
    def __init__( self ):
        # HPI struct SaHpiEntityPathT
        self.EntityImpacted = None
        # SaHpiDimiTestServiceImpactT
        self.ServiceImpact = None

#**
# HPI struct SaHpiDimiTestResultsT
#**
class SaHpiDimiTestResultsT:
    def __init__( self ):
        # SaHpiTimeT
        self.ResultTimeStamp = None
        # SaHpiTimeoutT
        self.RunDuration = None
        # SaHpiDimiTestRunStatusT
        self.LastRunStatus = None
        # SaHpiDimiTestErrCodeT
        self.TestErrorCode = None
        # HPI struct SaHpiTextBufferT
        self.TestResultString = None
        # SaHpiBoolT
        self.TestResultStringIsURI = None

#**
# HPI union SaHpiDimiTestParamValueT
#**
class SaHpiDimiTestParamValueT:
    def __init__( self ):
        # SaHpiInt32T
        self.paramint = None
        # SaHpiBoolT
        self.parambool = None
        # SaHpiFloat64T
        self.paramfloat = None
        # HPI struct SaHpiTextBufferT
        self.paramtext = None

#**
# HPI union SaHpiDimiTestParameterValueUnionT
#**
class SaHpiDimiTestParameterValueUnionT:
    def __init__( self ):
        # SaHpiInt32T
        self.IntValue = None
        # SaHpiFloat64T
        self.FloatValue = None

#**
# HPI struct SaHpiDimiTestParamsDefinitionT
#**
class SaHpiDimiTestParamsDefinitionT:
    def __init__( self ):
        # SaHpiUint8T[SAHPI_DIMITEST_PARAM_NAME_LEN]
        self.ParamName = None
        # HPI struct SaHpiTextBufferT
        self.ParamInfo = None
        # SaHpiDimiTestParamTypeT
        self.ParamType = None
        # HPI union SaHpiDimiTestParameterValueUnionT
        self.MinValue = None
        # HPI union SaHpiDimiTestParameterValueUnionT
        self.MaxValue = None
        # HPI union SaHpiDimiTestParamValueT
        self.DefaultParam = None

#**
# HPI struct SaHpiDimiTestT
#**
class SaHpiDimiTestT:
    def __init__( self ):
        # HPI struct SaHpiTextBufferT
        self.TestName = None
        # SaHpiDimiTestServiceImpactT
        self.ServiceImpact = None
        # SaHpiDimiTestAffectedEntityT[SAHPI_DIMITEST_MAX_ENTITIESIMPACTED]
        self.EntitiesImpacted = None
        # SaHpiBoolT
        self.NeedServiceOS = None
        # HPI struct SaHpiTextBufferT
        self.ServiceOS = None
        # SaHpiTimeT
        self.ExpectedRunDuration = None
        # SaHpiDimiTestCapabilityT
        self.TestCapabilities = None
        # SaHpiDimiTestParamsDefinitionT[SAHPI_DIMITEST_MAX_PARAMETERS]
        self.TestParameters = None

#**
# HPI struct SaHpiDimiTestVariableParamsT
#**
class SaHpiDimiTestVariableParamsT:
    def __init__( self ):
        # SaHpiUint8T[SAHPI_DIMITEST_PARAM_NAME_LEN]
        self.ParamName = None
        # SaHpiDimiTestParamTypeT
        self.ParamType = None
        # HPI union SaHpiDimiTestParamValueT
        self.Value = None

#**
# HPI struct SaHpiDimiInfoT
#**
class SaHpiDimiInfoT:
    def __init__( self ):
        # SaHpiUint32T
        self.NumberOfTests = None
        # SaHpiUint32T
        self.TestNumUpdateCounter = None

#**
# HPI struct SaHpiDimiRecT
#**
class SaHpiDimiRecT:
    def __init__( self ):
        # SaHpiDimiNumT
        self.DimiNum = None
        # SaHpiUint32T
        self.Oem = None

#**
# HPI struct SaHpiFumiSafDefinedSpecInfoT
#**
class SaHpiFumiSafDefinedSpecInfoT:
    def __init__( self ):
        # SaHpiFumiSafDefinedSpecIdT
        self.SpecID = None
        # SaHpiUint32T
        self.RevisionID = None

#**
# HPI struct SaHpiFumiOemDefinedSpecInfoT
#**
class SaHpiFumiOemDefinedSpecInfoT:
    def __init__( self ):
        # SaHpiManufacturerIdT
        self.Mid = None
        # SaHpiUint8T
        self.BodyLength = None
        # SaHpiUint8T[SAHPI_FUMI_MAX_OEM_BODY_LENGTH]
        self.Body = None

#**
# HPI union SaHpiFumiSpecInfoTypeUnionT
#**
class SaHpiFumiSpecInfoTypeUnionT:
    def __init__( self ):
        # HPI struct SaHpiFumiSafDefinedSpecInfoT
        self.SafDefined = None
        # HPI struct SaHpiFumiOemDefinedSpecInfoT
        self.OemDefined = None

#**
# HPI struct SaHpiFumiSpecInfoT
#**
class SaHpiFumiSpecInfoT:
    def __init__( self ):
        # SaHpiFumiSpecInfoTypeT
        self.SpecInfoType = None
        # HPI union SaHpiFumiSpecInfoTypeUnionT
        self.SpecInfoTypeUnion = None

#**
# HPI struct SaHpiFumiFirmwareInstanceInfoT
#**
class SaHpiFumiFirmwareInstanceInfoT:
    def __init__( self ):
        # SaHpiBoolT
        self.InstancePresent = None
        # HPI struct SaHpiTextBufferT
        self.Identifier = None
        # HPI struct SaHpiTextBufferT
        self.Description = None
        # HPI struct SaHpiTextBufferT
        self.DateTime = None
        # SaHpiUint32T
        self.MajorVersion = None
        # SaHpiUint32T
        self.MinorVersion = None
        # SaHpiUint32T
        self.AuxVersion = None

#**
# HPI struct SaHpiFumiImpactedEntityT
#**
class SaHpiFumiImpactedEntityT:
    def __init__( self ):
        # HPI struct SaHpiEntityPathT
        self.ImpactedEntity = None
        # SaHpiFumiServiceImpactT
        self.ServiceImpact = None

#**
# HPI struct SaHpiFumiServiceImpactDataT
#**
class SaHpiFumiServiceImpactDataT:
    def __init__( self ):
        # SaHpiUint32T
        self.NumEntities = None
        # SaHpiFumiImpactedEntityT[SAHPI_FUMI_MAX_ENTITIES_IMPACTED]
        self.ImpactedEntities = None

#**
# HPI struct SaHpiFumiSourceInfoT
#**
class SaHpiFumiSourceInfoT:
    def __init__( self ):
        # HPI struct SaHpiTextBufferT
        self.SourceUri = None
        # SaHpiFumiSourceStatusT
        self.SourceStatus = None
        # HPI struct SaHpiTextBufferT
        self.Identifier = None
        # HPI struct SaHpiTextBufferT
        self.Description = None
        # HPI struct SaHpiTextBufferT
        self.DateTime = None
        # SaHpiUint32T
        self.MajorVersion = None
        # SaHpiUint32T
        self.MinorVersion = None
        # SaHpiUint32T
        self.AuxVersion = None

#**
# HPI struct SaHpiFumiComponentInfoT
#**
class SaHpiFumiComponentInfoT:
    def __init__( self ):
        # SaHpiEntryIdT
        self.EntryId = None
        # SaHpiUint32T
        self.ComponentId = None
        # HPI struct SaHpiFumiFirmwareInstanceInfoT
        self.MainFwInstance = None
        # SaHpiUint32T
        self.ComponentFlags = None

#**
# HPI struct SaHpiFumiBankInfoT
#**
class SaHpiFumiBankInfoT:
    def __init__( self ):
        # SaHpiUint8T
        self.BankId = None
        # SaHpiUint32T
        self.BankSize = None
        # SaHpiUint32T
        self.Position = None
        # SaHpiFumiBankStateT
        self.BankState = None
        # HPI struct SaHpiTextBufferT
        self.Identifier = None
        # HPI struct SaHpiTextBufferT
        self.Description = None
        # HPI struct SaHpiTextBufferT
        self.DateTime = None
        # SaHpiUint32T
        self.MajorVersion = None
        # SaHpiUint32T
        self.MinorVersion = None
        # SaHpiUint32T
        self.AuxVersion = None

#**
# HPI struct SaHpiFumiLogicalBankInfoT
#**
class SaHpiFumiLogicalBankInfoT:
    def __init__( self ):
        # SaHpiUint8T
        self.FirmwarePersistentLocationCount = None
        # SaHpiFumiLogicalBankStateFlagsT
        self.BankStateFlags = None
        # HPI struct SaHpiFumiFirmwareInstanceInfoT
        self.PendingFwInstance = None
        # HPI struct SaHpiFumiFirmwareInstanceInfoT
        self.RollbackFwInstance = None

#**
# HPI struct SaHpiFumiLogicalComponentInfoT
#**
class SaHpiFumiLogicalComponentInfoT:
    def __init__( self ):
        # SaHpiEntryIdT
        self.EntryId = None
        # SaHpiUint32T
        self.ComponentId = None
        # HPI struct SaHpiFumiFirmwareInstanceInfoT
        self.PendingFwInstance = None
        # HPI struct SaHpiFumiFirmwareInstanceInfoT
        self.RollbackFwInstance = None
        # SaHpiUint32T
        self.ComponentFlags = None

#**
# HPI struct SaHpiFumiRecT
#**
class SaHpiFumiRecT:
    def __init__( self ):
        # SaHpiFumiNumT
        self.Num = None
        # SaHpiFumiProtocolT
        self.AccessProt = None
        # SaHpiFumiCapabilityT
        self.Capability = None
        # SaHpiUint8T
        self.NumBanks = None
        # SaHpiUint32T
        self.Oem = None

#**
# HPI struct SaHpiResourceEventT
#**
class SaHpiResourceEventT:
    def __init__( self ):
        # SaHpiResourceEventTypeT
        self.ResourceEventType = None

#**
# HPI struct SaHpiDomainEventT
#**
class SaHpiDomainEventT:
    def __init__( self ):
        # SaHpiDomainEventTypeT
        self.Type = None
        # SaHpiDomainIdT
        self.DomainId = None

#**
# HPI struct SaHpiSensorEventT
#**
class SaHpiSensorEventT:
    def __init__( self ):
        # SaHpiSensorNumT
        self.SensorNum = None
        # SaHpiSensorTypeT
        self.SensorType = None
        # SaHpiEventCategoryT
        self.EventCategory = None
        # SaHpiBoolT
        self.Assertion = None
        # SaHpiEventStateT
        self.EventState = None
        # SaHpiSensorOptionalDataT
        self.OptionalDataPresent = None
        # HPI struct SaHpiSensorReadingT
        self.TriggerReading = None
        # HPI struct SaHpiSensorReadingT
        self.TriggerThreshold = None
        # SaHpiEventStateT
        self.PreviousState = None
        # SaHpiEventStateT
        self.CurrentState = None
        # SaHpiUint32T
        self.Oem = None
        # SaHpiUint32T
        self.SensorSpecific = None

#**
# HPI struct SaHpiSensorEnableChangeEventT
#**
class SaHpiSensorEnableChangeEventT:
    def __init__( self ):
        # SaHpiSensorNumT
        self.SensorNum = None
        # SaHpiSensorTypeT
        self.SensorType = None
        # SaHpiEventCategoryT
        self.EventCategory = None
        # SaHpiBoolT
        self.SensorEnable = None
        # SaHpiBoolT
        self.SensorEventEnable = None
        # SaHpiEventStateT
        self.AssertEventMask = None
        # SaHpiEventStateT
        self.DeassertEventMask = None
        # SaHpiSensorEnableOptDataT
        self.OptionalDataPresent = None
        # SaHpiEventStateT
        self.CurrentState = None
        # SaHpiEventStateT
        self.CriticalAlarms = None
        # SaHpiEventStateT
        self.MajorAlarms = None
        # SaHpiEventStateT
        self.MinorAlarms = None

#**
# HPI struct SaHpiHotSwapEventT
#**
class SaHpiHotSwapEventT:
    def __init__( self ):
        # SaHpiHsStateT
        self.HotSwapState = None
        # SaHpiHsStateT
        self.PreviousHotSwapState = None
        # SaHpiHsCauseOfStateChangeT
        self.CauseOfStateChange = None

#**
# HPI struct SaHpiWatchdogEventT
#**
class SaHpiWatchdogEventT:
    def __init__( self ):
        # SaHpiWatchdogNumT
        self.WatchdogNum = None
        # SaHpiWatchdogActionEventT
        self.WatchdogAction = None
        # SaHpiWatchdogPretimerInterruptT
        self.WatchdogPreTimerAction = None
        # SaHpiWatchdogTimerUseT
        self.WatchdogUse = None

#**
# HPI struct SaHpiHpiSwEventT
#**
class SaHpiHpiSwEventT:
    def __init__( self ):
        # SaHpiManufacturerIdT
        self.MId = None
        # SaHpiSwEventTypeT
        self.Type = None
        # HPI struct SaHpiTextBufferT
        self.EventData = None

#**
# HPI struct SaHpiOemEventT
#**
class SaHpiOemEventT:
    def __init__( self ):
        # SaHpiManufacturerIdT
        self.MId = None
        # HPI struct SaHpiTextBufferT
        self.OemEventData = None

#**
# HPI struct SaHpiUserEventT
#**
class SaHpiUserEventT:
    def __init__( self ):
        # HPI struct SaHpiTextBufferT
        self.UserEventData = None

#**
# HPI struct SaHpiDimiEventT
#**
class SaHpiDimiEventT:
    def __init__( self ):
        # SaHpiDimiNumT
        self.DimiNum = None
        # SaHpiDimiTestNumT
        self.TestNum = None
        # SaHpiDimiTestRunStatusT
        self.DimiTestRunStatus = None
        # SaHpiDimiTestPercentCompletedT
        self.DimiTestPercentCompleted = None

#**
# HPI struct SaHpiDimiUpdateEventT
#**
class SaHpiDimiUpdateEventT:
    def __init__( self ):
        # SaHpiDimiNumT
        self.DimiNum = None

#**
# HPI struct SaHpiFumiEventT
#**
class SaHpiFumiEventT:
    def __init__( self ):
        # SaHpiFumiNumT
        self.FumiNum = None
        # SaHpiUint8T
        self.BankNum = None
        # SaHpiFumiUpgradeStatusT
        self.UpgradeStatus = None

#**
# HPI union SaHpiEventUnionT
#**
class SaHpiEventUnionT:
    def __init__( self ):
        # HPI struct SaHpiResourceEventT
        self.ResourceEvent = None
        # HPI struct SaHpiDomainEventT
        self.DomainEvent = None
        # HPI struct SaHpiSensorEventT
        self.SensorEvent = None
        # HPI struct SaHpiSensorEnableChangeEventT
        self.SensorEnableChangeEvent = None
        # HPI struct SaHpiHotSwapEventT
        self.HotSwapEvent = None
        # HPI struct SaHpiWatchdogEventT
        self.WatchdogEvent = None
        # HPI struct SaHpiHpiSwEventT
        self.HpiSwEvent = None
        # HPI struct SaHpiOemEventT
        self.OemEvent = None
        # HPI struct SaHpiUserEventT
        self.UserEvent = None
        # HPI struct SaHpiDimiEventT
        self.DimiEvent = None
        # HPI struct SaHpiDimiUpdateEventT
        self.DimiUpdateEvent = None
        # HPI struct SaHpiFumiEventT
        self.FumiEvent = None

#**
# HPI struct SaHpiEventT
#**
class SaHpiEventT:
    def __init__( self ):
        # SaHpiResourceIdT
        self.Source = None
        # SaHpiEventTypeT
        self.EventType = None
        # SaHpiTimeT
        self.Timestamp = None
        # SaHpiSeverityT
        self.Severity = None
        # HPI union SaHpiEventUnionT
        self.EventDataUnion = None

#**
# HPI struct SaHpiNameT
#**
class SaHpiNameT:
    def __init__( self ):
        # SaHpiUint16T
        self.Length = None
        # SaHpiUint8T[SA_HPI_MAX_NAME_LENGTH]
        self.Value = None

#**
# HPI struct SaHpiConditionT
#**
class SaHpiConditionT:
    def __init__( self ):
        # SaHpiStatusCondTypeT
        self.Type = None
        # HPI struct SaHpiEntityPathT
        self.Entity = None
        # SaHpiDomainIdT
        self.DomainId = None
        # SaHpiResourceIdT
        self.ResourceId = None
        # SaHpiSensorNumT
        self.SensorNum = None
        # SaHpiEventStateT
        self.EventState = None
        # HPI struct SaHpiNameT
        self.Name = None
        # SaHpiManufacturerIdT
        self.Mid = None
        # HPI struct SaHpiTextBufferT
        self.Data = None

#**
# HPI struct SaHpiAnnouncementT
#**
class SaHpiAnnouncementT:
    def __init__( self ):
        # SaHpiEntryIdT
        self.EntryId = None
        # SaHpiTimeT
        self.Timestamp = None
        # SaHpiBoolT
        self.AddedByUser = None
        # SaHpiSeverityT
        self.Severity = None
        # SaHpiBoolT
        self.Acknowledged = None
        # HPI struct SaHpiConditionT
        self.StatusCond = None

#**
# HPI struct SaHpiAnnunciatorRecT
#**
class SaHpiAnnunciatorRecT:
    def __init__( self ):
        # SaHpiAnnunciatorNumT
        self.AnnunciatorNum = None
        # SaHpiAnnunciatorTypeT
        self.AnnunciatorType = None
        # SaHpiBoolT
        self.ModeReadOnly = None
        # SaHpiUint32T
        self.MaxConditions = None
        # SaHpiUint32T
        self.Oem = None

#**
# HPI union SaHpiRdrTypeUnionT
#**
class SaHpiRdrTypeUnionT:
    def __init__( self ):
        # HPI struct SaHpiCtrlRecT
        self.CtrlRec = None
        # HPI struct SaHpiSensorRecT
        self.SensorRec = None
        # HPI struct SaHpiInventoryRecT
        self.InventoryRec = None
        # HPI struct SaHpiWatchdogRecT
        self.WatchdogRec = None
        # HPI struct SaHpiAnnunciatorRecT
        self.AnnunciatorRec = None
        # HPI struct SaHpiDimiRecT
        self.DimiRec = None
        # HPI struct SaHpiFumiRecT
        self.FumiRec = None

#**
# HPI struct SaHpiRdrT
#**
class SaHpiRdrT:
    def __init__( self ):
        # SaHpiEntryIdT
        self.RecordId = None
        # SaHpiRdrTypeT
        self.RdrType = None
        # HPI struct SaHpiEntityPathT
        self.Entity = None
        # SaHpiBoolT
        self.IsFru = None
        # HPI union SaHpiRdrTypeUnionT
        self.RdrTypeUnion = None
        # HPI struct SaHpiTextBufferT
        self.IdString = None

#**
# HPI struct SaHpiLoadIdT
#**
class SaHpiLoadIdT:
    def __init__( self ):
        # SaHpiLoadNumberT
        self.LoadNumber = None
        # HPI struct SaHpiTextBufferT
        self.LoadName = None

#**
# HPI struct SaHpiResourceInfoT
#**
class SaHpiResourceInfoT:
    def __init__( self ):
        # SaHpiUint8T
        self.ResourceRev = None
        # SaHpiUint8T
        self.SpecificVer = None
        # SaHpiUint8T
        self.DeviceSupport = None
        # SaHpiManufacturerIdT
        self.ManufacturerId = None
        # SaHpiUint16T
        self.ProductId = None
        # SaHpiUint8T
        self.FirmwareMajorRev = None
        # SaHpiUint8T
        self.FirmwareMinorRev = None
        # SaHpiUint8T
        self.AuxFirmwareRev = None
        # SaHpiUint8T[SAHPI_GUID_LENGTH]
        self.Guid = None

#**
# HPI struct SaHpiRptEntryT
#**
class SaHpiRptEntryT:
    def __init__( self ):
        # SaHpiEntryIdT
        self.EntryId = None
        # SaHpiResourceIdT
        self.ResourceId = None
        # HPI struct SaHpiResourceInfoT
        self.ResourceInfo = None
        # HPI struct SaHpiEntityPathT
        self.ResourceEntity = None
        # SaHpiCapabilitiesT
        self.ResourceCapabilities = None
        # SaHpiHsCapabilitiesT
        self.HotSwapCapabilities = None
        # SaHpiSeverityT
        self.ResourceSeverity = None
        # SaHpiBoolT
        self.ResourceFailed = None
        # HPI struct SaHpiTextBufferT
        self.ResourceTag = None

#**
# HPI struct SaHpiDomainInfoT
#**
class SaHpiDomainInfoT:
    def __init__( self ):
        # SaHpiDomainIdT
        self.DomainId = None
        # SaHpiDomainCapabilitiesT
        self.DomainCapabilities = None
        # SaHpiBoolT
        self.IsPeer = None
        # HPI struct SaHpiTextBufferT
        self.DomainTag = None
        # SaHpiUint32T
        self.DrtUpdateCount = None
        # SaHpiTimeT
        self.DrtUpdateTimestamp = None
        # SaHpiUint32T
        self.RptUpdateCount = None
        # SaHpiTimeT
        self.RptUpdateTimestamp = None
        # SaHpiUint32T
        self.DatUpdateCount = None
        # SaHpiTimeT
        self.DatUpdateTimestamp = None
        # SaHpiUint32T
        self.ActiveAlarms = None
        # SaHpiUint32T
        self.CriticalAlarms = None
        # SaHpiUint32T
        self.MajorAlarms = None
        # SaHpiUint32T
        self.MinorAlarms = None
        # SaHpiUint32T
        self.DatUserAlarmLimit = None
        # SaHpiBoolT
        self.DatOverflow = None
        # SaHpiUint8T[SAHPI_GUID_LENGTH]
        self.Guid = None

#**
# HPI struct SaHpiDrtEntryT
#**
class SaHpiDrtEntryT:
    def __init__( self ):
        # SaHpiEntryIdT
        self.EntryId = None
        # SaHpiDomainIdT
        self.DomainId = None
        # SaHpiBoolT
        self.IsPeer = None

#**
# HPI struct SaHpiAlarmT
#**
class SaHpiAlarmT:
    def __init__( self ):
        # SaHpiAlarmIdT
        self.AlarmId = None
        # SaHpiTimeT
        self.Timestamp = None
        # SaHpiSeverityT
        self.Severity = None
        # SaHpiBoolT
        self.Acknowledged = None
        # HPI struct SaHpiConditionT
        self.AlarmCond = None

#**
# HPI struct SaHpiEventLogInfoT
#**
class SaHpiEventLogInfoT:
    def __init__( self ):
        # SaHpiUint32T
        self.Entries = None
        # SaHpiUint32T
        self.Size = None
        # SaHpiUint32T
        self.UserEventMaxSize = None
        # SaHpiTimeT
        self.UpdateTimestamp = None
        # SaHpiTimeT
        self.CurrentTime = None
        # SaHpiBoolT
        self.Enabled = None
        # SaHpiBoolT
        self.OverflowFlag = None
        # SaHpiBoolT
        self.OverflowResetable = None
        # SaHpiEventLogOverflowActionT
        self.OverflowAction = None

#**
# HPI struct SaHpiEventLogEntryT
#**
class SaHpiEventLogEntryT:
    def __init__( self ):
        # SaHpiEventLogEntryIdT
        self.EntryId = None
        # SaHpiTimeT
        self.Timestamp = None
        # HPI struct SaHpiEventT
        self.Event = None


